/// GENERATED FILE. DO NOT EDIT BY HAND.
///
/// Generated by tool/generate_chunk_runtime_data.dart from:
/// - `assets/authoring/level/level_defs.json`
/// Stable identifiers for level definitions.
///
/// Avoid renaming or reordering values; treat as protocol-stable.
enum LevelId { forest, field }
