/// GENERATED FILE. DO NOT EDIT BY HAND.
///
/// Generated by tool/generate_chunk_runtime_data.dart from:
/// - `assets/authoring/level/level_defs.json`
/// Registry for core level definitions.
library;

import '../collision/static_world_geometry.dart';
import '../track/authored_chunk_patterns.dart';
import '../track/chunk_pattern_source.dart';
import 'level_assembly.dart';
import 'level_definition.dart';
import 'level_id.dart';

/// Default runtime-authored chunk pattern source.
final ChunkPatternSource defaultChunkPatternSource =
    authoredChunkPatternSourceForLevel(LevelId.field.name);

const StaticWorldGeometry _forestBaseGeometry = StaticWorldGeometry(
  groundPlane: StaticGroundPlane(topY: 224.0),
);

const StaticWorldGeometry _fieldBaseGeometry = StaticWorldGeometry(
  groundPlane: StaticGroundPlane(topY: 224.0),
);

/// Resolves level definitions by stable [LevelId].
class LevelRegistry {
  const LevelRegistry._();

  /// Returns the level definition for a given [LevelId].
  static LevelDefinition byId(LevelId id) {
    switch (id) {
      case LevelId.forest:
        return LevelDefinition(
          id: LevelId.forest,
          chunkPatternSource: authoredChunkPatternSourceForLevel(
            LevelId.forest.name,
          ),
          cameraCenterY: 135.0,
          staticWorldGeometry: _forestBaseGeometry,
          earlyPatternChunks: 3,
          easyPatternChunks: 0,
          normalPatternChunks: 0,
          noEnemyChunks: 3,
          visualThemeId: 'forest',
        );
      case LevelId.field:
        return LevelDefinition(
          id: LevelId.field,
          chunkPatternSource: authoredChunkPatternSourceForLevel(
            LevelId.field.name,
          ),
          cameraCenterY: 135.0,
          staticWorldGeometry: _fieldBaseGeometry,
          earlyPatternChunks: 3,
          easyPatternChunks: 0,
          normalPatternChunks: 0,
          noEnemyChunks: 3,
          visualThemeId: 'field',
          assembly: const LevelAssemblyDefinition(
            loopSegments: true,
            segments: <LevelAssemblySegment>[
              LevelAssemblySegment(
                segmentId: 'field_run',
                groupId: 'default',
                minChunkCount: 2,
                maxChunkCount: 2,
                requireDistinctChunks: false,
              ),
              LevelAssemblySegment(
                segmentId: 'forest_run',
                groupId: 'forest',
                minChunkCount: 1,
                maxChunkCount: 1,
                requireDistinctChunks: false,
              ),
              LevelAssemblySegment(
                segmentId: 'none_run',
                groupId: 'none',
                minChunkCount: 1,
                maxChunkCount: 1,
                requireDistinctChunks: false,
              ),
            ],
          ),
        );
    }
  }
}
