/// GENERATED FILE. DO NOT EDIT BY HAND.
///
/// Generated by tool/generate_chunk_runtime_data.dart from:
/// - `assets/authoring/level/level_defs.json`
/// Registry for core level definitions.
library;

import '../track/authored_chunk_patterns.dart';
import '../track/chunk_pattern_source.dart';

import 'level_definition.dart';
import 'level_id.dart';

/// Default runtime-authored chunk pattern source.
final ChunkPatternSource defaultChunkPatternSource =
    authoredChunkPatternSourceForLevel(LevelId.field.name);

/// Resolves level definitions by stable [LevelId].
class LevelRegistry {
  const LevelRegistry._();

  /// Returns the level definition for a given [LevelId].
  static LevelDefinition byId(LevelId id) {
    switch (id) {
      case LevelId.forest:
        return LevelDefinition(
          id: LevelId.forest,
          chunkPatternSource: authoredChunkPatternSourceForLevel(
            LevelId.forest.name,
          ),
          cameraCenterY: 135.0,
          groundTopY: 224.0,
          earlyPatternChunks: 3,
          easyPatternChunks: 10,
          normalPatternChunks: 15,
          noEnemyChunks: 3,
          visualThemeId: 'forest',
        );
      case LevelId.field:
        return LevelDefinition(
          id: LevelId.field,
          chunkPatternSource: authoredChunkPatternSourceForLevel(
            LevelId.field.name,
          ),
          cameraCenterY: 135.0,
          groundTopY: 222.0,
          earlyPatternChunks: 3,
          easyPatternChunks: 0,
          normalPatternChunks: 0,
          noEnemyChunks: 3,
          visualThemeId: 'field',
        );
      case LevelId.new_level:
        return LevelDefinition(
          id: LevelId.new_level,
          chunkPatternSource: authoredChunkPatternSourceForLevel(
            LevelId.new_level.name,
          ),
          cameraCenterY: 135.0,
          groundTopY: 224.0,
          earlyPatternChunks: 3,
          easyPatternChunks: 10,
          normalPatternChunks: 15,
          noEnemyChunks: 3,
          visualThemeId: 'new_level',
        );
    }
  }
}
