import '../../combat/ancient_god_pose_catalog.dart';
import '../../combat/damage_type.dart';
import '../../enemies/enemy_id.dart';
import '../../bosses/boss_utility_delivery.dart';
import '../../projectiles/projectile_id.dart';
import '../../spell_impacts/spell_impact_id.dart';
import '../../snapshots/enums.dart';
import '../ability_def.dart';

/// 60 Hz authored timings; shared cooldowns leave room between readable threats.
final Map<AbilityKey, AbilityDef> ancientGodAbilityDefs = {
  'goddess.claw_combo': AbilityDef(
    id: 'goddess.claw_combo',
    category: AbilityCategory.melee,
    hitDelivery: const MeleeHitDelivery(
      profile: AncientGodPoseCatalog.goddessClaws,
      hitPolicy: HitPolicy.oncePerTarget,
    ),
    baseDamage: 700,
    baseDamageType: DamageType.physical,
    windupTicks: 24,
    activeTicks: 54,
    recoveryTicks: 18,
    cooldownTicks: 150,
    cooldownGroupId: 0,
    animKey: AnimKey.strike,
  ),
  'goddess.orb': AbilityDef(
    id: 'goddess.orb',
    category: AbilityCategory.ranged,
    hitDelivery: const ProjectileHitDelivery(
      projectileId: ProjectileId.goddessOrb,
    ),
    baseDamage: 600,
    baseDamageType: DamageType.dark,
    windupTicks: 42,
    activeTicks: 6,
    recoveryTicks: 24,
    cooldownTicks: 110,
    cooldownGroupId: 0,
    animKey: AnimKey.cast,
  ),
  'goddess.eruption': AbilityDef(
    id: 'goddess.eruption',
    category: AbilityCategory.ranged,
    hitDelivery: const TargetPointHitDelivery(
      profile: AncientGodPoseCatalog.goddessEruption,
      stepTimeSeconds: .08,
      hitPolicy: HitPolicy.oncePerTarget,
      impactEffectId: SpellImpactId.goddessEruption,
      anchor: TargetPointAnchor.surfaceBelow,
    ),
    baseDamage: 700,
    baseDamageType: DamageType.dark,
    windupTicks: 60,
    activeTicks: 6,
    recoveryTicks: 36,
    cooldownTicks: 140,
    cooldownGroupId: 0,
    animKey: AnimKey.ranged,
  ),
  'goddess.teleport': AbilityDef(
    id: 'goddess.teleport',
    category: AbilityCategory.utility,
    hitDelivery: const BossTeleportDelivery(),
    baseDamage: 0,
    baseDamageType: DamageType.physical,
    windupTicks: 24,
    activeTicks: 1,
    recoveryTicks: 30,
    cooldownTicks: 100,
    cooldownGroupId: 0,
    animKey: AnimKey.teleportOut,
  ),
  'shoggoth.tentacle_sweep': AbilityDef(
    id: 'shoggoth.tentacle_sweep',
    category: AbilityCategory.melee,
    hitDelivery: const MeleeHitDelivery(
      profile: AncientGodPoseCatalog.shoggothSweep,
      hitPolicy: HitPolicy.oncePerTarget,
    ),
    baseDamage: 700,
    baseDamageType: DamageType.physical,
    windupTicks: 24,
    activeTicks: 24,
    recoveryTicks: 18,
    cooldownTicks: 100,
    cooldownGroupId: 0,
    animKey: AnimKey.strike,
  ),
  'shoggoth.spinning_charge': AbilityDef(
    id: 'shoggoth.spinning_charge',
    category: AbilityCategory.melee,
    hitDelivery: const MeleeHitDelivery(
      profile: AncientGodPoseCatalog.shoggothSpin,
      hitPolicy: HitPolicy.oncePerTarget,
    ),
    baseDamage: 600,
    baseDamageType: DamageType.physical,
    windupTicks: 30,
    activeTicks: 36,
    recoveryTicks: 24,
    cooldownTicks: 140,
    cooldownGroupId: 0,
    animKey: AnimKey.strike2,
  ),
  'shoggoth.orb': AbilityDef(
    id: 'shoggoth.orb',
    category: AbilityCategory.ranged,
    hitDelivery: const ProjectileHitDelivery(
      projectileId: ProjectileId.shoggothOrb,
    ),
    baseDamage: 600,
    baseDamageType: DamageType.dark,
    windupTicks: 42,
    activeTicks: 6,
    recoveryTicks: 24,
    cooldownTicks: 110,
    cooldownGroupId: 0,
    animKey: AnimKey.cast,
  ),
  'shoggoth.summon': AbilityDef(
    id: 'shoggoth.summon',
    category: AbilityCategory.utility,
    hitDelivery: const BossSummonDelivery(
      enemyId: EnemyId.shoggothMinion,
      maxAlive: 3,
      lifetimeSeconds: 12,
    ),
    baseDamage: 0,
    baseDamageType: DamageType.physical,
    windupTicks: 42,
    activeTicks: 6,
    recoveryTicks: 18,
    cooldownTicks: 150,
    cooldownGroupId: 0,
    animKey: AnimKey.ranged,
  ),
  'shoggoth.teleport': AbilityDef(
    id: 'shoggoth.teleport',
    category: AbilityCategory.utility,
    hitDelivery: const BossTeleportDelivery(),
    baseDamage: 0,
    baseDamageType: DamageType.physical,
    windupTicks: 36,
    activeTicks: 1,
    recoveryTicks: 54,
    cooldownTicks: 110,
    cooldownGroupId: 0,
    animKey: AnimKey.teleportOut,
  ),
  'voidcaller.vertical_beam': AbilityDef(
    id: 'voidcaller.vertical_beam',
    category: AbilityCategory.ranged,
    hitDelivery: const TargetPointHitDelivery(
      profile: AncientGodPoseCatalog.voidVerticalBeam,
      stepTimeSeconds: .08,
      hitPolicy: HitPolicy.oncePerTarget,
      impactEffectId: SpellImpactId.voidVerticalBeam,
      anchor: TargetPointAnchor.surfaceBelow,
    ),
    baseDamage: 700,
    baseDamageType: DamageType.dark,
    windupTicks: 48,
    activeTicks: 6,
    recoveryTicks: 24,
    cooldownTicks: 130,
    cooldownGroupId: 0,
    animKey: AnimKey.cast,
  ),
  'voidcaller.diagonal_beam': AbilityDef(
    id: 'voidcaller.diagonal_beam',
    category: AbilityCategory.ranged,
    hitDelivery: const TargetPointHitDelivery(
      profile: AncientGodPoseCatalog.voidDiagonalBeam,
      stepTimeSeconds: .08,
      hitPolicy: HitPolicy.oncePerTarget,
      impactEffectId: SpellImpactId.voidDiagonalBeam,
      anchor: TargetPointAnchor.surfaceBelow,
    ),
    baseDamage: 700,
    baseDamageType: DamageType.dark,
    windupTicks: 48,
    activeTicks: 6,
    recoveryTicks: 24,
    cooldownTicks: 130,
    cooldownGroupId: 0,
    animKey: AnimKey.ranged,
  ),
  'voidcaller.claw': AbilityDef(
    id: 'voidcaller.claw',
    category: AbilityCategory.ranged,
    hitDelivery: const ProjectileHitDelivery(
      projectileId: ProjectileId.voidClaw,
    ),
    baseDamage: 600,
    baseDamageType: DamageType.fire,
    windupTicks: 36,
    activeTicks: 6,
    recoveryTicks: 24,
    cooldownTicks: 100,
    cooldownGroupId: 0,
    animKey: AnimKey.strike2,
  ),
  'voidcaller.summon': AbilityDef(
    id: 'voidcaller.summon',
    category: AbilityCategory.utility,
    hitDelivery: const BossSummonDelivery(
      enemyId: EnemyId.voidTentacle,
      maxAlive: 2,
      lifetimeSeconds: 12,
    ),
    baseDamage: 0,
    baseDamageType: DamageType.physical,
    windupTicks: 60,
    activeTicks: 6,
    recoveryTicks: 24,
    cooldownTicks: 150,
    cooldownGroupId: 0,
    animKey: AnimKey.ranged,
  ),
  'shoggoth_minion.bite': AbilityDef(
    id: 'shoggoth_minion.bite',
    category: AbilityCategory.melee,
    hitDelivery: const MeleeHitDelivery(
      profile: AncientGodPoseCatalog.minionBite,
      hitPolicy: HitPolicy.oncePerTarget,
    ),
    baseDamage: 200,
    baseDamageType: DamageType.physical,
    windupTicks: 24,
    activeTicks: 12,
    recoveryTicks: 18,
    cooldownTicks: 90,
    cooldownGroupId: 0,
    animKey: AnimKey.strike,
  ),
  'void_tentacle.lash': AbilityDef(
    id: 'void_tentacle.lash',
    category: AbilityCategory.melee,
    hitDelivery: const MeleeHitDelivery(
      profile: AncientGodPoseCatalog.tentacleLash,
      hitPolicy: HitPolicy.oncePerTarget,
    ),
    baseDamage: 300,
    baseDamageType: DamageType.physical,
    windupTicks: 30,
    activeTicks: 18,
    recoveryTicks: 18,
    cooldownTicks: 110,
    cooldownGroupId: 0,
    animKey: AnimKey.strike,
  ),
};
