import 'package:flutter/foundation.dart';

import '../workspace/editor_workspace.dart';

/// Immutable command envelope sent from UI/session to a domain plugin.
///
/// [kind] is plugin-defined and should be stable across one editor version.
/// [payload] carries command arguments as JSON-like scalar/map/list values.
@immutable
class AuthoringCommand {
  const AuthoringCommand({
    required this.kind,
    this.payload = const <String, Object?>{},
  });

  final String kind;
  final Map<String, Object?> payload;
}

/// Plugin-owned immutable source-of-truth snapshot for one authoring domain.
///
/// Implementations should treat instances as value snapshots suitable for
/// undo/redo history and deterministic recomputation.
abstract class AuthoringDocument {
  const AuthoringDocument();
}

/// UI-facing projection derived from an [AuthoringDocument].
///
/// This can be optimized for editing/rendering concerns, but it must remain
/// deterministic for identical document input.
abstract class EditableScene {
  const EditableScene();
}

/// Validation levels used by domain plugins.
enum ValidationSeverity { info, warning, error }

/// One plugin validation finding for the current document state.
///
/// [code] should remain stable for a specific issue type so UI/tests can match
/// without parsing [message]. [sourcePath] is optional and points to the file
/// most closely associated with the issue when known.
@immutable
class ValidationIssue {
  const ValidationIssue({
    required this.severity,
    required this.code,
    required this.message,
    this.sourcePath,
  });

  final ValidationSeverity severity;
  final String code;
  final String message;
  final String? sourcePath;
}

/// Human-readable export byproduct (summary, diff, diagnostics, etc.).
@immutable
class ExportArtifact {
  const ExportArtifact({required this.title, required this.content});

  final String title;
  final String content;
}

/// Result of a plugin export operation.
///
/// [applied] indicates whether repository files were actually written.
/// Session orchestration uses this to decide whether to reload workspace state.
@immutable
class ExportResult {
  const ExportResult({
    required this.applied,
    this.artifacts = const <ExportArtifact>[],
  });

  final bool applied;
  final List<ExportArtifact> artifacts;
}

/// One pending file change preview generated by a plugin.
///
/// [relativePath] is workspace-relative and [unifiedDiff] is display-oriented
/// text, not a guaranteed apply-ready patch format.
@immutable
class PendingFileDiff {
  const PendingFileDiff({
    required this.relativePath,
    required this.editCount,
    required this.unifiedDiff,
  });

  final String relativePath;
  final int editCount;
  final String unifiedDiff;
}

/// Plugin-reported pending-change summary for unsaved edits.
///
/// Keep [changedEntryIds] and [fileDiffs] coherent: if there are material
/// edits, both should generally describe the same change set.
@immutable
class PendingChanges {
  const PendingChanges({
    this.changedEntryIds = const <String>[],
    this.fileDiffs = const <PendingFileDiff>[],
  });

  final List<String> changedEntryIds;
  final List<PendingFileDiff> fileDiffs;

  /// Fast unsaved-changes gate used by session/UI.
  ///
  /// Checks both entry ids and file diffs so this remains correct even if one
  /// side is accidentally left empty by a plugin implementation.
  bool get hasChanges => changedEntryIds.isNotEmpty || fileDiffs.isNotEmpty;
}

/// Domain adapter contract between editor session orchestration and a concrete
/// authoring implementation (entities/prefabs/chunks).
abstract class AuthoringDomainPlugin {
  /// Stable unique plugin identifier used for route/session selection.
  String get id;

  /// Loads domain data from repository files under [workspace].
  Future<AuthoringDocument> loadFromRepo(EditorWorkspace workspace);

  /// Validates [document] and returns deterministic issue ordering.
  List<ValidationIssue> validate(AuthoringDocument document);

  /// Builds the UI-editable scene projection for [document].
  EditableScene buildEditableScene(AuthoringDocument document);

  /// Applies one edit command to [document].
  ///
  /// Return the original instance when command is a no-op so session-level
  /// undo/redo does not record unnecessary history entries.
  AuthoringDocument applyEdit(
    AuthoringDocument document,
    AuthoringCommand command,
  );

  /// Exports [document] to repository files.
  ///
  /// Returns [ExportResult.applied] false when no file writes were needed.
  Future<ExportResult> exportToRepo(
    EditorWorkspace workspace, {
    required AuthoringDocument document,
  });

  /// Describes file/entry deltas for [document] against repository baseline.
  PendingChanges describePendingChanges(
    EditorWorkspace workspace, {
    required AuthoringDocument document,
  });
}
