import 'package:flutter/foundation.dart';

import '../workspace/editor_workspace.dart';

/// Immutable command envelope sent from UI/session to a domain plugin.
///
/// [kind] is plugin-defined and should be stable across one editor version.
/// [payload] carries command arguments as JSON-like scalar/map/list values or
/// immutable typed snapshots owned by the caller.
@immutable
class AuthoringCommand {
  AuthoringCommand({
    required this.kind,
    Map<String, Object?> payload = const <String, Object?>{},
  }) : payload = Map<String, Object?>.unmodifiable(
         payload.map(
           (key, value) =>
               MapEntry<String, Object?>(key, _freezePayloadValue(value)),
         ),
       );

  final String kind;
  final Map<String, Object?> payload;

  static Object? _freezePayloadValue(Object? value) {
    if (value is Map<Object?, Object?>) {
      return Map<Object?, Object?>.unmodifiable(
        value.map(
          (key, nestedValue) =>
              MapEntry<Object?, Object?>(key, _freezePayloadValue(nestedValue)),
        ),
      );
    }
    if (value is List<Object?>) {
      return List<Object?>.unmodifiable(value.map(_freezePayloadValue));
    }
    return value;
  }
}

/// Plugin-owned immutable source-of-truth snapshot for one authoring domain.
///
/// Implementations should treat instances as value snapshots suitable for
/// undo/redo history and deterministic recomputation.
abstract class AuthoringDocument {
  const AuthoringDocument();
}

/// UI-facing projection derived from an [AuthoringDocument].
///
/// This can be optimized for editing/rendering concerns, but it must remain
/// deterministic for identical document input.
abstract class EditableScene {
  const EditableScene();
}

/// Validation levels used by domain plugins.
enum ValidationSeverity { info, warning, error }

/// One plugin validation finding for the current document state.
///
/// [code] should remain stable for a specific issue type so UI/tests can match
/// without parsing [message]. [sourcePath] is optional and points to the file
/// most closely associated with the issue when known.
@immutable
class ValidationIssue {
  const ValidationIssue({
    required this.severity,
    required this.code,
    required this.message,
    this.sourcePath,
  });

  final ValidationSeverity severity;
  final String code;
  final String message;
  final String? sourcePath;
}

/// Human-readable export byproduct (summary, diff, diagnostics, etc.).
@immutable
class ExportArtifact {
  const ExportArtifact({required this.title, required this.content});

  final String title;
  final String content;
}

/// Result of a plugin export operation.
///
/// [applied] indicates whether repository files were actually written.
/// Session orchestration uses this to decide whether to reload workspace state.
@immutable
class ExportResult {
  ExportResult({
    required this.applied,
    List<ExportArtifact> artifacts = const <ExportArtifact>[],
  }) : artifacts = List<ExportArtifact>.unmodifiable(artifacts);

  final bool applied;
  final List<ExportArtifact> artifacts;
}

/// One pending file change preview generated by a plugin.
///
/// [relativePath] is workspace-relative and [unifiedDiff] is display-oriented
/// text, not a guaranteed apply-ready patch format.
@immutable
class PendingFileDiff {
  const PendingFileDiff({
    required this.relativePath,
    required this.editCount,
    required this.unifiedDiff,
  });

  final String relativePath;
  final int editCount;
  final String unifiedDiff;
}

/// Plugin-reported pending-change summary for unsaved edits.
///
/// [changedItemIds] contains domain-defined opaque ids for changed authoring
/// objects when the UI needs per-item dirty state. [fileDiffs] describes the
/// pending file writes. A domain may populate one or both collections depending
/// on the workflow it supports.
@immutable
class PendingChanges {
  PendingChanges({
    List<String> changedItemIds = const <String>[],
    List<PendingFileDiff> fileDiffs = const <PendingFileDiff>[],
  }) : changedItemIds = List<String>.unmodifiable(changedItemIds),
       fileDiffs = List<PendingFileDiff>.unmodifiable(fileDiffs);

  static const PendingChanges empty = PendingChanges._empty();

  const PendingChanges._empty()
    : changedItemIds = const <String>[],
      fileDiffs = const <PendingFileDiff>[];

  final List<String> changedItemIds;
  final List<PendingFileDiff> fileDiffs;

  /// Fast unsaved-changes gate used by session/UI.
  ///
  /// Checks both item ids and file diffs so this remains correct even if one
  /// side is accidentally left empty by a plugin implementation.
  bool get hasChanges => changedItemIds.isNotEmpty || fileDiffs.isNotEmpty;
}

/// Domain adapter contract between editor session orchestration and a concrete
/// authoring implementation (entities/prefabs/chunks).
abstract class AuthoringDomainPlugin {
  /// Stable unique plugin identifier used for route/session selection.
  String get id;

  /// Loads domain data from repository files under [workspace].
  Future<AuthoringDocument> loadFromRepo(EditorWorkspace workspace);

  /// Validates [document] and returns deterministic issue ordering.
  List<ValidationIssue> validate(AuthoringDocument document);

  /// Builds the UI-editable scene projection for [document].
  EditableScene buildEditableScene(AuthoringDocument document);

  /// Applies one edit command to [document].
  ///
  /// Return the original instance when command is a no-op so session-level
  /// undo/redo does not record unnecessary history entries.
  AuthoringDocument applyEdit(
    AuthoringDocument document,
    AuthoringCommand command,
  );

  /// Exports [document] to repository files.
  ///
  /// Returns [ExportResult.applied] false when no file writes were needed.
  Future<ExportResult> exportToRepo(
    EditorWorkspace workspace, {
    required AuthoringDocument document,
  });

  /// Describes file/item deltas for [document] against repository baseline.
  PendingChanges describePendingChanges(
    EditorWorkspace workspace, {
    required AuthoringDocument document,
  });
}
