// Generated by tools/combat/generate_ancient_god_effects.py; do not edit.
import '../contracts/render_anim_set_definition.dart';
import '../contracts/render_frame_part.dart';
import '../contracts/render_frame_rect.dart';
import '../snapshots/enums.dart';
import '../util/vec2.dart';

/// Portal, beam and surface impact share the twelve-frame damage clock.
abstract final class AncientGodEffectCatalog {
  static const vertical = RenderAnimSetDefinition(
    frameWidth: 138,
    frameHeight: 146,
    anchorPoint: Vec2(92, 146),
    sourcesByKey: {
      AnimKey.hit:
          'entities/enemies/ancient_god_pack/voidcaller/sprite_sheet.png',
    },
    frameCountsByKey: {AnimKey.hit: 12},
    stepTimeSecondsByKey: {AnimKey.hit: .08},
    compositeFramesByKey: {
      AnimKey.hit: [
        [
          RenderFramePart(
            source: RenderFrameRect(69, 779, 26, 13),
            position: Vec2(79, 19.5),
            size: Vec2(26, 13),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(69, 779, 26, 13),
            position: Vec2(79, 133),
            size: Vec2(26, 13),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(232, 779, 41, 12),
            position: Vec2(71.5, 20),
            size: Vec2(41, 12),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(232, 779, 41, 12),
            position: Vec2(71.5, 134),
            size: Vec2(41, 12),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(408, 778, 31, 12),
            position: Vec2(76.5, 20),
            size: Vec2(31, 12),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(408, 778, 31, 12),
            position: Vec2(76.5, 134),
            size: Vec2(31, 12),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(579, 778, 30, 17),
            position: Vec2(77, 17.5),
            size: Vec2(30, 17),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(579, 778, 30, 17),
            position: Vec2(77, 129),
            size: Vec2(30, 17),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(750, 776, 34, 38),
            position: Vec2(75, 7),
            size: Vec2(34, 38),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(750, 776, 34, 38),
            position: Vec2(75, 108),
            size: Vec2(34, 38),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(63, 1324, 40, 34),
            position: Vec2(72, 9),
            size: Vec2(40, 34),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(248, 1029, 12, 32),
            position: Vec2(86.5, 26),
            size: Vec2(11, 112),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(67, 1197, 33, 25),
            position: Vec2(75.5, 121),
            size: Vec2(33, 25),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(234, 1324, 40, 34),
            position: Vec2(72, 9),
            size: Vec2(40, 34),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(76, 1029, 14, 32),
            position: Vec2(86.5, 26),
            size: Vec2(11, 112),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(238, 1197, 34, 25),
            position: Vec2(75, 121),
            size: Vec2(34, 25),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(407, 1323, 39, 35),
            position: Vec2(72.5, 8.5),
            size: Vec2(39, 35),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(248, 1029, 12, 32),
            position: Vec2(86.5, 26),
            size: Vec2(11, 112),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(409, 1197, 33, 25),
            position: Vec2(75.5, 121),
            size: Vec2(33, 25),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(577, 1322, 42, 36),
            position: Vec2(71, 8),
            size: Vec2(42, 36),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(76, 1029, 14, 32),
            position: Vec2(86.5, 26),
            size: Vec2(11, 112),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(579, 1197, 34, 25),
            position: Vec2(75, 121),
            size: Vec2(34, 25),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(747, 1322, 41, 36),
            position: Vec2(71.5, 8),
            size: Vec2(41, 36),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(248, 1029, 12, 32),
            position: Vec2(86.5, 26),
            size: Vec2(11, 112),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(751, 1197, 34, 25),
            position: Vec2(75, 121),
            size: Vec2(34, 25),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(919, 1323, 38, 35),
            position: Vec2(73, 8.5),
            size: Vec2(38, 35),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(925, 1197, 31, 25),
            position: Vec2(76.5, 121),
            size: Vec2(31, 25),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(919, 1323, 38, 35),
            position: Vec2(73, 8.5),
            size: Vec2(38, 35),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(925, 1197, 31, 25),
            position: Vec2(76.5, 121),
            size: Vec2(31, 25),
            rotationRadians: 0,
          ),
        ],
      ],
    },
  );
  static const diagonal = RenderAnimSetDefinition(
    frameWidth: 138,
    frameHeight: 146,
    anchorPoint: Vec2(92, 146),
    sourcesByKey: {
      AnimKey.hit:
          'entities/enemies/ancient_god_pack/voidcaller/sprite_sheet.png',
    },
    frameCountsByKey: {AnimKey.hit: 12},
    stepTimeSecondsByKey: {AnimKey.hit: .08},
    compositeFramesByKey: {
      AnimKey.hit: [
        [
          RenderFramePart(
            source: RenderFrameRect(80, 1454, 26, 13),
            position: Vec2(19, 19.5),
            size: Vec2(26, 13),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(80, 1454, 26, 13),
            position: Vec2(79, 133),
            size: Vec2(26, 13),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(243, 1454, 41, 12),
            position: Vec2(11.5, 20),
            size: Vec2(41, 12),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(243, 1454, 41, 12),
            position: Vec2(71.5, 134),
            size: Vec2(41, 12),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(419, 1453, 31, 12),
            position: Vec2(16.5, 20),
            size: Vec2(31, 12),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(419, 1453, 31, 12),
            position: Vec2(76.5, 134),
            size: Vec2(31, 12),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(590, 1453, 30, 17),
            position: Vec2(17, 17.5),
            size: Vec2(30, 17),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(590, 1453, 30, 17),
            position: Vec2(77, 129),
            size: Vec2(30, 17),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(761, 1451, 34, 43),
            position: Vec2(15, 4.5),
            size: Vec2(34, 43),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(761, 1451, 34, 43),
            position: Vec2(75, 103),
            size: Vec2(34, 43),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(70, 1998, 43, 40),
            position: Vec2(10.5, 6),
            size: Vec2(43, 40),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(248, 1029, 12, 32),
            position: Vec2(26.5, 26),
            size: Vec2(11, 127.059),
            rotationRadians: -0.491809175988699,
          ),
          RenderFramePart(
            source: RenderFrameRect(53, 1870, 49, 32),
            position: Vec2(67.5, 114),
            size: Vec2(49, 32),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(242, 1998, 42, 40),
            position: Vec2(11, 6),
            size: Vec2(42, 40),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(76, 1029, 14, 32),
            position: Vec2(26.5, 26),
            size: Vec2(11, 127.059),
            rotationRadians: -0.491809175988699,
          ),
          RenderFramePart(
            source: RenderFrameRect(223, 1870, 49, 32),
            position: Vec2(67.5, 114),
            size: Vec2(49, 32),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(412, 1997, 44, 41),
            position: Vec2(10, 5.5),
            size: Vec2(44, 41),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(248, 1029, 12, 32),
            position: Vec2(26.5, 26),
            size: Vec2(11, 127.059),
            rotationRadians: -0.491809175988699,
          ),
          RenderFramePart(
            source: RenderFrameRect(394, 1870, 50, 32),
            position: Vec2(67, 114),
            size: Vec2(50, 32),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(584, 1996, 45, 42),
            position: Vec2(9.5, 5),
            size: Vec2(45, 42),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(76, 1029, 14, 32),
            position: Vec2(26.5, 26),
            size: Vec2(11, 127.059),
            rotationRadians: -0.491809175988699,
          ),
          RenderFramePart(
            source: RenderFrameRect(571, 1870, 43, 32),
            position: Vec2(70.5, 114),
            size: Vec2(43, 32),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(754, 1996, 44, 42),
            position: Vec2(10, 5),
            size: Vec2(44, 42),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(248, 1029, 12, 32),
            position: Vec2(26.5, 26),
            size: Vec2(11, 127.059),
            rotationRadians: -0.491809175988699,
          ),
          RenderFramePart(
            source: RenderFrameRect(740, 1870, 46, 32),
            position: Vec2(69, 114),
            size: Vec2(46, 32),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(926, 1997, 41, 41),
            position: Vec2(11.5, 5.5),
            size: Vec2(41, 41),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(912, 1870, 44, 32),
            position: Vec2(70, 114),
            size: Vec2(44, 32),
            rotationRadians: 0,
          ),
        ],
        [
          RenderFramePart(
            source: RenderFrameRect(926, 1997, 41, 41),
            position: Vec2(11.5, 5.5),
            size: Vec2(41, 41),
            rotationRadians: 0,
          ),
          RenderFramePart(
            source: RenderFrameRect(912, 1870, 44, 32),
            position: Vec2(70, 114),
            size: Vec2(44, 32),
            rotationRadians: 0,
          ),
        ],
      ],
    },
  );
}
