import 'dart:math' as math;

import '../collision/terrain/terrain_edge.dart';
import '../collision/terrain/terrain_edge_id.dart';
import '../collision/terrain/terrain_numeric.dart';
import '../collision/terrain/terrain_polygon.dart';
import '../collision/terrain/terrain_query_buffer.dart';
import '../collision/terrain/terrain_traversal_cache.dart';
import '../collision/terrain/terrain_traversal_profile.dart';
import '../enemies/enemy_catalog.dart';
import '../enemies/enemy_id.dart';
import '../enemies/enemy_terrain_profile.dart';
import '../snapshots/enums.dart';
import 'terrain_placement_query.dart';
import 'types/terrain_navigation_surface.dart';

/// Authored support intent retained until polygon-terrain placement resolves.
enum TerrainSpawnSupportSelection {
  /// The requested entity is airborne and needs clearance only.
  none,

  /// The marker targets ordinary ground at its authored support height.
  ground,

  /// The marker or procedural item targets the highest surface at its X.
  highestSurfaceAtX,

  /// The marker targets a solid obstacle top, never a one-way fallback.
  obstacleTop,

  /// A deferred edge spawn targets its requested support without relocation.
  deferredEdge,
}

/// Procedural AABB item category retained in placement diagnostics.
enum TerrainSpawnItemKind {
  /// Score collectible generated by the chunk spawn loop.
  collectible,

  /// Health, mana, or stamina restoration pickup.
  restoration,
}

/// Explicit shape and terrain policy used by one spawn placement request.
sealed class TerrainSpawnPlacementProfile {
  const TerrainSpawnPlacementProfile();

  /// Stable schema key used by placement diagnostics.
  String get diagnosticKey;
}

/// Catalog-derived capsule policy for one enemy spawn.
final class TerrainEnemySpawnPlacementProfile
    extends TerrainSpawnPlacementProfile {
  /// Resolves one enemy's facing-aware capsule and traversal policy.
  factory TerrainEnemySpawnPlacementProfile.fromCatalog({
    required EnemyCatalog catalog,
    required EnemyId enemyId,
    required Facing facing,
  }) {
    final archetype = catalog.get(enemyId);
    final contact = catalog.terrainContactProfile(enemyId);
    final facingSign = facing == archetype.artFacingDir ? 1 : -1;
    return TerrainEnemySpawnPlacementProfile._(
      enemyId: enemyId,
      motionKind: contact.motionKind,
      capsule: TerrainPlacementCapsule(
        radiusTicks: contact.capsule.radiusTicks,
        verticalHalfSegmentTicks: contact.capsule.verticalHalfSegmentTicks,
        resolvedOffsetXTicks: contact.capsule.offsetXTicks * facingSign,
        offsetYTicks: contact.capsule.offsetYTicks,
      ),
      traversalProfile: contact.traversal,
    );
  }

  const TerrainEnemySpawnPlacementProfile._({
    required this.enemyId,
    required this.motionKind,
    required this.capsule,
    required this.traversalProfile,
  });

  /// Catalog identity that owns the shape and terrain policy.
  final EnemyId enemyId;

  /// Whether placement is grounded, flying-clearance, or kinematic-only.
  final EnemyTerrainMotionKind motionKind;

  /// Facing-resolved upright capsule used for support and clearance.
  final TerrainPlacementCapsule capsule;

  /// Catalog-owned slope, one-way, and contact eligibility policy.
  final TerrainTraversalProfile traversalProfile;

  @override
  String get diagnosticKey => 'enemy:${enemyId.name}';
}

/// Player-traversable support and full-AABB policy for a procedural item.
final class TerrainItemSpawnPlacementProfile
    extends TerrainSpawnPlacementProfile {
  /// Quantizes authored item dimensions and player support policy once.
  factory TerrainItemSpawnPlacementProfile.fromWorld({
    required TerrainSpawnItemKind itemKind,
    required double width,
    required double height,
    required double supportClearance,
    required double noSpawnMargin,
    required TerrainTraversalProfile traversalProfile,
    double minimumSupportSpan = 20,
  }) {
    if (width <= 0 ||
        height <= 0 ||
        supportClearance < 0 ||
        noSpawnMargin < 0 ||
        minimumSupportSpan <= 0) {
      throw ArgumentError(
        'Item dimensions/support span must be positive and clearances '
        'non-negative.',
      );
    }
    final halfWidthTicks = physicsCoordinateToTicks(
      width * 0.5,
      name: 'itemHalfWidth',
    );
    final halfHeightTicks = physicsCoordinateToTicks(
      height * 0.5,
      name: 'itemHalfHeight',
    );
    final marginTicks = physicsCoordinateToTicks(
      noSpawnMargin,
      name: 'itemNoSpawnMargin',
    );
    final authoredMinimumSpanTicks = physicsCoordinateToTicks(
      minimumSupportSpan,
      name: 'itemMinimumSupportSpan',
    );
    return TerrainItemSpawnPlacementProfile._(
      itemKind: itemKind,
      halfWidthTicks: halfWidthTicks,
      halfHeightTicks: halfHeightTicks,
      supportClearanceTicks: physicsCoordinateToTicks(
        supportClearance,
        name: 'itemSupportClearance',
      ),
      noSpawnMarginTicks: marginTicks,
      minimumSupportSpanTicks: math.max(
        authoredMinimumSpanTicks,
        2 * (halfWidthTicks + marginTicks),
      ),
      traversalProfile: traversalProfile,
    );
  }

  const TerrainItemSpawnPlacementProfile._({
    required this.itemKind,
    required this.halfWidthTicks,
    required this.halfHeightTicks,
    required this.supportClearanceTicks,
    required this.noSpawnMarginTicks,
    required this.minimumSupportSpanTicks,
    required this.traversalProfile,
  });

  /// Stable item category used in diagnostics.
  final TerrainSpawnItemKind itemKind;

  /// Horizontal half extent in authoritative physics ticks.
  final int halfWidthTicks;

  /// Vertical half extent in authoritative physics ticks.
  final int halfHeightTicks;

  /// Existing authored vertical gap above the selected support.
  final int supportClearanceTicks;

  /// Existing authored AABB expansion used by no-spawn checks.
  final int noSpawnMarginTicks;

  /// Required total horizontal support span, including item edge margins.
  final int minimumSupportSpanTicks;

  /// Player traversal policy used to decide which surfaces can hold items.
  final TerrainTraversalProfile traversalProfile;

  @override
  String get diagnosticKey => 'item:${itemKind.name}';
}

/// Immutable request for the shared legacy/terrain spawn-placement boundary.
///
/// Coordinates use authoritative 1/1024-world-unit physics ticks. The desired
/// Y is the historical candidate used by legacy authority; supported terrain
/// profiles derive their accepted Y from the selected polygon edge instead.
final class TerrainSpawnPlacementRequest {
  /// Creates a validated placement request without querying world geometry.
  factory TerrainSpawnPlacementRequest({
    required TerrainSpawnPlacementProfile profile,
    required TerrainPoint desiredBodyCenter,
    required TerrainSpawnSupportSelection supportSelection,
    int? requestedSupportYTicks,
    TerrainEdgeId? intendedSupportEdgeId,
    bool intendedSourceAvailable = true,
    bool allowSameSupportClamp = false,
  }) {
    final isFlying =
        profile is TerrainEnemySpawnPlacementProfile &&
        profile.motionKind == EnemyTerrainMotionKind.flyingDynamic;
    if (supportSelection == TerrainSpawnSupportSelection.none && !isFlying) {
      throw ArgumentError(
        'Only flying enemy placement may omit terrain support.',
      );
    }
    final needsBridgeY =
        intendedSupportEdgeId == null &&
        supportSelection == TerrainSpawnSupportSelection.deferredEdge;
    if (needsBridgeY && requestedSupportYTicks == null) {
      throw ArgumentError(
        'Deferred placement needs support Y or an exact edge ID.',
      );
    }
    if (allowSameSupportClamp &&
        (supportSelection == TerrainSpawnSupportSelection.none ||
            profile is TerrainItemSpawnPlacementProfile)) {
      throw ArgumentError(
        'Same-support clamping is limited to supported actor placement.',
      );
    }
    return TerrainSpawnPlacementRequest._(
      profile: profile,
      desiredBodyCenter: desiredBodyCenter,
      supportSelection: supportSelection,
      requestedSupportYTicks: requestedSupportYTicks,
      intendedSupportEdgeId: intendedSupportEdgeId,
      intendedSourceAvailable: intendedSourceAvailable,
      allowSameSupportClamp: allowSameSupportClamp,
    );
  }

  const TerrainSpawnPlacementRequest._({
    required this.profile,
    required this.desiredBodyCenter,
    required this.supportSelection,
    required this.requestedSupportYTicks,
    required this.intendedSupportEdgeId,
    required this.intendedSourceAvailable,
    required this.allowSameSupportClamp,
  });

  /// Complete actor/item shape and terrain-eligibility policy.
  final TerrainSpawnPlacementProfile profile;

  /// Historical candidate retained exactly by legacy authority.
  final TerrainPoint desiredBodyCenter;

  /// Authored source-selection intent that terrain authority must preserve.
  final TerrainSpawnSupportSelection supportSelection;

  /// Optional legacy support-height bridge when no exact edge ID is supplied.
  ///
  /// Runtime ground and obstacle selection use terrain semantics when this is
  /// absent. Deferred edge placement remains height-bound.
  final int? requestedSupportYTicks;

  /// Exact intended polygon edge; this bypasses legacy height matching.
  final TerrainEdgeId? intendedSupportEdgeId;

  /// Whether the authored source actually resolved instead of using fallback Y.
  final bool intendedSourceAvailable;

  /// Allows the nearest valid X only on the selected finite support edge.
  final bool allowSameSupportClamp;
}

/// Immutable accepted transform or typed rejection from one spawn query.
final class TerrainSpawnPlacementResult {
  TerrainSpawnPlacementResult._({
    required this.profileKey,
    required this.supportSelection,
    required this.validity,
    required this.geometryVersion,
    required this.requestedBodyCenter,
    required this.bodyCenter,
    required this.supportPoint,
    required this.supportEdgeId,
    required this.blockingEdgeId,
    required this.absoluteSlopeAngleUnits,
    required this.sameSupportClamped,
    required this.intendedSupportEdgeId,
  }) : diagnostic = _spawnPlacementDiagnostic(
         profileKey: profileKey,
         supportSelection: supportSelection,
         validity: validity,
         geometryVersion: geometryVersion,
         requestedBodyCenter: requestedBodyCenter,
         bodyCenter: bodyCenter,
         supportPoint: supportPoint,
         supportEdgeId: supportEdgeId,
         blockingEdgeId: blockingEdgeId,
         absoluteSlopeAngleUnits: absoluteSlopeAngleUnits,
         sameSupportClamped: sameSupportClamped,
         intendedSupportEdgeId: intendedSupportEdgeId,
       );

  /// Preserves the historical candidate exactly under rectangle authority.
  factory TerrainSpawnPlacementResult.legacyAccepted(
    TerrainSpawnPlacementRequest request,
  ) => TerrainSpawnPlacementResult._(
    profileKey: request.profile.diagnosticKey,
    supportSelection: request.supportSelection,
    validity: TerrainPlacementValidity.valid,
    geometryVersion: null,
    requestedBodyCenter: request.desiredBodyCenter,
    bodyCenter: request.desiredBodyCenter,
    supportPoint: request.requestedSupportYTicks == null
        ? null
        : TerrainPoint(
            request.desiredBodyCenter.xTicks,
            request.requestedSupportYTicks!,
          ),
    supportEdgeId: null,
    blockingEdgeId: null,
    absoluteSlopeAngleUnits:
        request.supportSelection == TerrainSpawnSupportSelection.none
        ? null
        : 0,
    sameSupportClamped: false,
    intendedSupportEdgeId: request.intendedSupportEdgeId,
  );

  /// Stable actor/item key included in [diagnostic].
  final String profileKey;

  /// Authored selection mode copied from the request.
  final TerrainSpawnSupportSelection supportSelection;

  /// Typed acceptance or terminal rejection reason.
  final TerrainPlacementValidity validity;

  /// Polygon geometry version, or `null` for legacy rectangle authority.
  final int? geometryVersion;

  /// Original body candidate before support projection or clamping.
  final TerrainPoint requestedBodyCenter;

  /// Accepted body center, or `null` for a rejected attempt.
  final TerrainPoint? bodyCenter;

  /// Exact selected support projection, when support selection succeeded.
  final TerrainPoint? supportPoint;

  /// Canonical selected support edge, when one was found.
  final TerrainEdgeId? supportEdgeId;

  /// First canonical edge that prevented full clearance.
  final TerrainEdgeId? blockingEdgeId;

  /// Selected support's absolute quantized angle, when applicable.
  final int? absoluteSlopeAngleUnits;

  /// Whether actor placement used the nearest X on the same finite edge.
  final bool sameSupportClamped;

  /// Exact authored edge requested by the caller, when available.
  final TerrainEdgeId? intendedSupportEdgeId;

  /// Canonical integer record suitable for authoring and deterministic tests.
  final String diagnostic;

  /// Whether the candidate has a commit-ready [bodyCenter].
  bool get accepted => validity == TerrainPlacementValidity.valid;
}

/// Derf's independent Core-owned horizontal perch-span requirement.
const int derfMinimumSupportSpanTicks = 32 * terrainPhysicsTicksPerWorldUnit;

/// Resolves every Phase 3 enemy/item spawn against one terrain surface set.
///
/// Selection happens before profile filtering, so an invalid intended or
/// highest surface is terminal and never redirects a spawn to lower terrain.
final class TerrainSpawnPlacementResolver {
  /// Creates a resolver over one immutable geometry/surface publication.
  TerrainSpawnPlacementResolver({required TerrainPlacementQuery placementQuery})
    : _placementQuery = placementQuery,
      _terrainBuffer = placementQuery.terrainIndex.createQueryBuffer();

  final TerrainPlacementQuery _placementQuery;
  final TerrainQueryBuffer _terrainBuffer;

  /// Resolves [request] without mutating ECS state or consuming random values.
  TerrainSpawnPlacementResult resolve(TerrainSpawnPlacementRequest request) {
    if (request.supportSelection != TerrainSpawnSupportSelection.none &&
        !request.intendedSourceAvailable) {
      return _failure(request, TerrainPlacementValidity.intendedSupportMissing);
    }
    return switch (request.profile) {
      TerrainEnemySpawnPlacementProfile profile => _resolveEnemy(
        request,
        profile,
      ),
      TerrainItemSpawnPlacementProfile profile => _resolveItem(
        request,
        profile,
      ),
    };
  }

  TerrainSpawnPlacementResult _resolveEnemy(
    TerrainSpawnPlacementRequest request,
    TerrainEnemySpawnPlacementProfile profile,
  ) {
    if (profile.motionKind == EnemyTerrainMotionKind.flyingDynamic) {
      final result = _placementQuery.validateClearance(
        TerrainClearancePlacementRequest(
          bodyCenter: request.desiredBodyCenter,
          capsule: profile.capsule,
          traversalProfile: profile.traversalProfile,
          oneWayClearancePolicy: TerrainOneWayClearancePolicy.ignore,
          expectedGeometryVersion: _placementQuery.geometry.version,
        ),
      );
      return _fromPlacementResult(request, result);
    }

    if (profile.motionKind == EnemyTerrainMotionKind.kinematicPlacement &&
        (profile.enemyId != EnemyId.derf ||
            request.supportSelection !=
                TerrainSpawnSupportSelection.obstacleTop)) {
      return _failure(request, TerrainPlacementValidity.profileIneligible);
    }

    final support = _selectSupport(request, request.desiredBodyCenter.xTicks);
    if (support == null) {
      return _failure(
        request,
        request.intendedSupportEdgeId != null ||
                request.supportSelection !=
                    TerrainSpawnSupportSelection.highestSurfaceAtX
            ? TerrainPlacementValidity.intendedSupportMissing
            : TerrainPlacementValidity.noSupport,
      );
    }
    final isDerf = profile.enemyId == EnemyId.derf;
    final result = _placementQuery.resolveGrounded(
      TerrainGroundPlacementRequest(
        desiredBodyCenterXTicks: request.desiredBodyCenter.xTicks,
        minimumSupportYTicks: math.min(
          support.start.yTicks,
          support.end.yTicks,
        ),
        maximumSupportYTicks: math.max(
          support.start.yTicks,
          support.end.yTicks,
        ),
        capsule: profile.capsule,
        traversalProfile: profile.traversalProfile,
        supportRequirement: const TerrainSupportRequirement.groundedSpawn(),
        minimumSupportSpanTicks: isDerf ? derfMinimumSupportSpanTicks : 0,
        intendedSupportEdgeId: support.id,
        allowSameSupportClamp: request.allowSameSupportClamp,
        oneWayClearancePolicy: isDerf
            ? TerrainOneWayClearancePolicy.ignore
            : TerrainOneWayClearancePolicy.useTraversalProfile,
        expectedGeometryVersion: _placementQuery.geometry.version,
      ),
    );
    return _fromPlacementResult(request, result);
  }

  TerrainSpawnPlacementResult _resolveItem(
    TerrainSpawnPlacementRequest request,
    TerrainItemSpawnPlacementProfile profile,
  ) {
    final support = _selectSupport(request, request.desiredBodyCenter.xTicks);
    if (support == null) {
      return _failure(
        request,
        request.intendedSupportEdgeId != null
            ? TerrainPlacementValidity.intendedSupportMissing
            : TerrainPlacementValidity.noSupport,
      );
    }
    if (!support.isEligibleFor(profile.traversalProfile)) {
      return _failure(
        request,
        TerrainPlacementValidity.profileIneligible,
        support: support,
      );
    }
    if (support.dxTicks < profile.minimumSupportSpanTicks) {
      return _failure(
        request,
        TerrainPlacementValidity.insufficientSupportWidth,
        support: support,
      );
    }

    final centerX = request.desiredBodyCenter.xTicks;
    final supportInset = _divideCeil(profile.minimumSupportSpanTicks, 2);
    if (centerX < support.xMinTicks + supportInset ||
        centerX > support.xMaxTicks - supportInset) {
      return _failure(
        request,
        TerrainPlacementValidity.outsideStandableRange,
        support: support,
      );
    }

    final supportY = support.yAtXTicks(centerX);
    final bodyCenter = TerrainPoint(
      centerX,
      supportY - profile.supportClearanceTicks - profile.halfHeightTicks,
    );
    final blocker = _firstAabbBlocker(bodyCenter, profile);
    return TerrainSpawnPlacementResult._(
      profileKey: profile.diagnosticKey,
      supportSelection: request.supportSelection,
      validity: blocker == null
          ? TerrainPlacementValidity.valid
          : TerrainPlacementValidity.blockedClearance,
      geometryVersion: _placementQuery.geometry.version,
      requestedBodyCenter: request.desiredBodyCenter,
      bodyCenter: blocker == null ? bodyCenter : null,
      supportPoint: TerrainPoint(centerX, supportY),
      supportEdgeId: support.id,
      blockingEdgeId: blocker,
      absoluteSlopeAngleUnits: terrainAbsoluteSlopeAngleUnits(
        dxTicks: support.dxTicks,
        dyTicks: support.dyTicks,
        tangentXTicks: support.tangent.xTicks,
        tangentYTicks: support.tangent.yTicks,
      ),
      sameSupportClamped: false,
      intendedSupportEdgeId: request.intendedSupportEdgeId,
    );
  }

  TerrainNavigationSurface? _selectSupport(
    TerrainSpawnPlacementRequest request,
    int queryX,
  ) {
    final exactId = request.intendedSupportEdgeId;
    if (exactId != null) {
      return _placementQuery.surfaceIndex.surfaceSet.surfaceById(exactId);
    }

    TerrainNavigationSurface? selected;
    for (final surface in _placementQuery.surfaceIndex.surfaces) {
      if (queryX < surface.xMinTicks || queryX > surface.xMaxTicks) continue;
      final supportY = surface.yAtXTicks(queryX);
      switch (request.supportSelection) {
        case TerrainSpawnSupportSelection.none:
          continue;
        case TerrainSpawnSupportSelection.highestSurfaceAtX:
          if (selected == null ||
              supportY < selected.yAtXTicks(queryX) ||
              (supportY == selected.yAtXTicks(queryX) &&
                  surface.id.compareTo(selected.id) < 0)) {
            selected = surface;
          }
        case TerrainSpawnSupportSelection.ground:
          final requestedY = request.requestedSupportYTicks;
          if (surface.collisionMode != TerrainCollisionMode.solid ||
              (requestedY == null
                  ? surface.surfaceKind != 'ground'
                  : supportY != requestedY)) {
            continue;
          }
          if (_isHigherPrioritySurface(surface, selected, queryX)) {
            selected = surface;
          }
        case TerrainSpawnSupportSelection.obstacleTop:
          final requestedY = request.requestedSupportYTicks;
          final isAuthoredObstacle =
              surface.id.placementKey != null ||
              surface.surfaceKind == 'obstacle';
          if (surface.collisionMode != TerrainCollisionMode.solid ||
              (requestedY == null
                  ? !isAuthoredObstacle
                  : supportY != requestedY)) {
            continue;
          }
          if (_isHigherPrioritySurface(surface, selected, queryX)) {
            selected = surface;
          }
        case TerrainSpawnSupportSelection.deferredEdge:
          if (supportY != request.requestedSupportYTicks) continue;
          if (selected == null || surface.id.compareTo(selected.id) < 0) {
            selected = surface;
          }
      }
    }
    return selected;
  }

  static bool _isHigherPrioritySurface(
    TerrainNavigationSurface candidate,
    TerrainNavigationSurface? current,
    int queryX,
  ) {
    if (current == null) return true;
    final candidateY = candidate.yAtXTicks(queryX);
    final currentY = current.yAtXTicks(queryX);
    return candidateY < currentY ||
        (candidateY == currentY && candidate.id.compareTo(current.id) < 0);
  }

  TerrainEdgeId? _firstAabbBlocker(
    TerrainPoint center,
    TerrainItemSpawnPlacementProfile profile,
  ) {
    final bounds = TerrainAabb(
      minX: center.xTicks - profile.halfWidthTicks,
      minY: center.yTicks - profile.halfHeightTicks,
      maxX: center.xTicks + profile.halfWidthTicks,
      maxY: center.yTicks + profile.halfHeightTicks,
    ).expanded(profile.noSpawnMarginTicks);
    _placementQuery.terrainIndex.query(bounds, _terrainBuffer);
    for (var index = 0; index < _terrainBuffer.candidateCount; index += 1) {
      final edge = _terrainBuffer.edgeAt(
        index,
        _placementQuery.terrainIndex.edges,
      );
      if (edge.collisionMode == TerrainCollisionMode.oneWay &&
          !(edge.dxTicks > 0 && edge.outwardNormal.yTicks < 0)) {
        continue;
      }
      if (_segmentIntersectsOpenAabb(edge, bounds)) return edge.id;
    }

    for (final polygon in _placementQuery.geometry.polygons) {
      if (polygon.collisionMode != TerrainCollisionMode.solid) continue;
      if (_aabbPointInsidePolygon(bounds, polygon.vertices)) {
        return _firstPolygonEdgeId(polygon);
      }
    }
    return null;
  }

  TerrainEdgeId? _firstPolygonEdgeId(TerrainPolygon polygon) {
    final identity = polygon.identity;
    for (final edge in _placementQuery.geometry.edges) {
      final id = edge.id;
      if (id.chunkIndex == identity.chunkIndex &&
          id.chunkKey == identity.chunkKey &&
          id.placementKey == identity.placementKey &&
          id.shapeId == identity.shapeId) {
        return id;
      }
    }
    return null;
  }

  TerrainSpawnPlacementResult _fromPlacementResult(
    TerrainSpawnPlacementRequest request,
    TerrainPlacementResult result,
  ) => TerrainSpawnPlacementResult._(
    profileKey: request.profile.diagnosticKey,
    supportSelection: request.supportSelection,
    validity: result.validity,
    geometryVersion: result.geometryVersion,
    requestedBodyCenter: request.desiredBodyCenter,
    bodyCenter: result.isValid ? result.bodyCenter : null,
    supportPoint: result.supportPoint,
    supportEdgeId: result.supportEdgeId,
    blockingEdgeId: result.blockingEdgeId,
    absoluteSlopeAngleUnits: result.absoluteSlopeAngleUnits,
    sameSupportClamped: result.sameSupportClampedBodyXTicks != null,
    intendedSupportEdgeId: request.intendedSupportEdgeId,
  );

  TerrainSpawnPlacementResult _failure(
    TerrainSpawnPlacementRequest request,
    TerrainPlacementValidity validity, {
    TerrainNavigationSurface? support,
  }) => TerrainSpawnPlacementResult._(
    profileKey: request.profile.diagnosticKey,
    supportSelection: request.supportSelection,
    validity: validity,
    geometryVersion: _placementQuery.geometry.version,
    requestedBodyCenter: request.desiredBodyCenter,
    bodyCenter: null,
    supportPoint: null,
    supportEdgeId: support?.id,
    blockingEdgeId: null,
    absoluteSlopeAngleUnits: support == null
        ? null
        : terrainAbsoluteSlopeAngleUnits(
            dxTicks: support.dxTicks,
            dyTicks: support.dyTicks,
            tangentXTicks: support.tangent.xTicks,
            tangentYTicks: support.tangent.yTicks,
          ),
    sameSupportClamped: false,
    intendedSupportEdgeId: request.intendedSupportEdgeId,
  );
}

bool _segmentIntersectsOpenAabb(TerrainEdge edge, TerrainAabb bounds) {
  final minEdgeX = math.min(edge.start.xTicks, edge.end.xTicks);
  final maxEdgeX = math.max(edge.start.xTicks, edge.end.xTicks);
  final minEdgeY = math.min(edge.start.yTicks, edge.end.yTicks);
  final maxEdgeY = math.max(edge.start.yTicks, edge.end.yTicks);
  if (maxEdgeX <= bounds.minX ||
      minEdgeX >= bounds.maxX ||
      maxEdgeY <= bounds.minY ||
      minEdgeY >= bounds.maxY) {
    return false;
  }

  final edgeX = edge.end.xTicks - edge.start.xTicks;
  final edgeY = edge.end.yTicks - edge.start.yTicks;
  final normalX = -edgeY;
  final normalY = edgeX;
  final lineProjection =
      normalX * edge.start.xTicks + normalY * edge.start.yTicks;
  final minimumProjection =
      normalX * (normalX >= 0 ? bounds.minX : bounds.maxX) +
      normalY * (normalY >= 0 ? bounds.minY : bounds.maxY);
  final maximumProjection =
      normalX * (normalX >= 0 ? bounds.maxX : bounds.minX) +
      normalY * (normalY >= 0 ? bounds.maxY : bounds.minY);
  return lineProjection > minimumProjection &&
      lineProjection < maximumProjection;
}

bool _aabbPointInsidePolygon(TerrainAabb bounds, List<TerrainPoint> vertices) {
  final points = <TerrainPoint>[
    TerrainPoint(
      (bounds.minX + bounds.maxX) >> 1,
      (bounds.minY + bounds.maxY) >> 1,
    ),
    TerrainPoint(bounds.minX, bounds.minY),
    TerrainPoint(bounds.maxX, bounds.minY),
    TerrainPoint(bounds.minX, bounds.maxY),
    TerrainPoint(bounds.maxX, bounds.maxY),
  ];
  return points.any((point) => _pointStrictlyInsidePolygon(point, vertices));
}

bool _pointStrictlyInsidePolygon(
  TerrainPoint point,
  List<TerrainPoint> vertices,
) {
  var inside = false;
  for (
    var currentIndex = 0, previousIndex = vertices.length - 1;
    currentIndex < vertices.length;
    previousIndex = currentIndex, currentIndex += 1
  ) {
    final current = vertices[currentIndex];
    final previous = vertices[previousIndex];
    final edgeX = current.xTicks - previous.xTicks;
    final edgeY = current.yTicks - previous.yTicks;
    final relativeX = point.xTicks - previous.xTicks;
    final relativeY = point.yTicks - previous.yTicks;
    if (edgeX * relativeY - edgeY * relativeX == 0 &&
        point.xTicks >= math.min(previous.xTicks, current.xTicks) &&
        point.xTicks <= math.max(previous.xTicks, current.xTicks) &&
        point.yTicks >= math.min(previous.yTicks, current.yTicks) &&
        point.yTicks <= math.max(previous.yTicks, current.yTicks)) {
      return false;
    }
    final crossesY =
        (current.yTicks > point.yTicks) != (previous.yTicks > point.yTicks);
    if (!crossesY) continue;
    final left =
        (point.xTicks - current.xTicks) * (previous.yTicks - current.yTicks);
    final right =
        (previous.xTicks - current.xTicks) * (point.yTicks - current.yTicks);
    final crossesRight = previous.yTicks > current.yTicks
        ? left < right
        : left > right;
    if (crossesRight) inside = !inside;
  }
  return inside;
}

int _divideCeil(int numerator, int positiveDenominator) =>
    (numerator + positiveDenominator - 1) ~/ positiveDenominator;

String _spawnPlacementDiagnostic({
  required String profileKey,
  required TerrainSpawnSupportSelection supportSelection,
  required TerrainPlacementValidity validity,
  required int? geometryVersion,
  required TerrainPoint requestedBodyCenter,
  required TerrainPoint? bodyCenter,
  required TerrainPoint? supportPoint,
  required TerrainEdgeId? supportEdgeId,
  required TerrainEdgeId? blockingEdgeId,
  required int? absoluteSlopeAngleUnits,
  required bool sameSupportClamped,
  required TerrainEdgeId? intendedSupportEdgeId,
}) =>
    'terrain-spawn-placement-v1'
    '|profile=$profileKey'
    '|selection=${supportSelection.name}'
    '|validity=${validity.name}'
    '|geometry=${geometryVersion ?? 'legacy'}'
    '|requested=${requestedBodyCenter.xTicks},${requestedBodyCenter.yTicks}'
    '|body=${bodyCenter?.xTicks ?? '-'},${bodyCenter?.yTicks ?? '-'}'
    '|intended=${intendedSupportEdgeId?.canonicalKey ?? '-'}'
    '|support=${supportEdgeId?.canonicalKey ?? '-'}'
    '|point=${supportPoint?.xTicks ?? '-'},${supportPoint?.yTicks ?? '-'}'
    '|blocker=${blockingEdgeId?.canonicalKey ?? '-'}'
    '|slope=${absoluteSlopeAngleUnits ?? '-'}'
    '|clamped=${sameSupportClamped ? 1 : 0}';
