// Generated by tool/generate_chunk_runtime_data.dart.
// Do not edit by hand.

part of 'terrain_material_registry.dart';

const Map<String, TerrainMaterialSpec> _authoredTerrainMaterials =
    <String, TerrainMaterialSpec>{
      'grass_dirt': TerrainMaterialSpec(
        key: 'grass_dirt',
        displayName: 'Grass / Dirt',
        revision: 11,
        fill: TerrainMaterialImageRegionSpec(
          assetPath: 'level/atlases/tiny_swords/ground.png',
          x: 224,
          y: 192,
          width: 32,
          height: 32,
        ),
        top: TerrainMaterialEdgeProfileSpec(
          base: TerrainMaterialEdgeLayerSpec(
            region: TerrainMaterialImageRegionSpec(
              assetPath: 'level/atlases/tiny_swords/ground.png',
              x: 32,
              y: 1,
              width: 32,
              height: 31,
            ),
            anchorY: 0.0,
          ),
        ),
        leftWall: TerrainMaterialEdgeProfileSpec(
          base: TerrainMaterialEdgeLayerSpec(
            region: TerrainMaterialImageRegionSpec(
              assetPath: 'level/atlases/tiny_swords/ground.png',
              x: 193,
              y: 192,
              width: 31,
              height: 32,
            ),
            anchorY: 0.0,
          ),
        ),
        rightWall: TerrainMaterialEdgeProfileSpec(
          base: TerrainMaterialEdgeLayerSpec(
            region: TerrainMaterialImageRegionSpec(
              assetPath: 'level/atlases/tiny_swords/ground.png',
              x: 256,
              y: 192,
              width: 31,
              height: 32,
            ),
            anchorY: 0.0,
          ),
        ),
        underside: TerrainMaterialEdgeProfileSpec(
          base: TerrainMaterialEdgeLayerSpec(
            region: TerrainMaterialImageRegionSpec(
              assetPath: 'level/atlases/tiny_swords/ground.png',
              x: 32,
              y: 64,
              width: 32,
              height: 31,
            ),
            anchorY: 0.0,
          ),
        ),
        topStartCap: TerrainMaterialCapSpec(
          region: TerrainMaterialImageRegionSpec(
            assetPath: 'level/atlases/tiny_swords/ground.png',
            x: 0,
            y: 1,
            width: 32,
            height: 31,
          ),
          anchorX: 0.0,
          anchorY: 0.0,
        ),
        topEndCap: TerrainMaterialCapSpec(
          region: TerrainMaterialImageRegionSpec(
            assetPath: 'level/atlases/tiny_swords/ground.png',
            x: 64,
            y: 1,
            width: 32,
            height: 31,
          ),
          anchorX: 32.0,
          anchorY: 0.0,
        ),
        undersideStartCap: TerrainMaterialCapSpec(
          region: TerrainMaterialImageRegionSpec(
            assetPath: 'level/atlases/tiny_swords/ground.png',
            x: 64,
            y: 64,
            width: 32,
            height: 31,
          ),
          anchorX: 0.0,
          anchorY: 0.0,
        ),
        undersideEndCap: TerrainMaterialCapSpec(
          region: TerrainMaterialImageRegionSpec(
            assetPath: 'level/atlases/tiny_swords/ground.png',
            x: 0,
            y: 64,
            width: 32,
            height: 31,
          ),
          anchorX: 32.0,
          anchorY: 0.0,
        ),
      ),
    };
