// Generated by tool/generate_chunk_runtime_data.dart.
// Do not edit by hand.

part of 'terrain_material_registry.dart';

const Map<String, TerrainMaterialSpec> _authoredTerrainMaterials =
    <String, TerrainMaterialSpec>{
      'grass_dirt': TerrainMaterialSpec(
        key: 'grass_dirt',
        displayName: 'Grass / Dirt',
        revision: 1,
        fill: TerrainMaterialImageRegionSpec(
          assetPath: 'terrain/tx_tileset_ground/atlas.png',
          x: 32,
          y: 32,
          width: 32,
          height: 32,
        ),
        top: TerrainMaterialEdgeProfileSpec(
          base: TerrainMaterialEdgeLayerSpec(
            region: TerrainMaterialImageRegionSpec(
              assetPath: 'terrain/tx_tileset_ground/atlas.png',
              x: 32,
              y: 0,
              width: 32,
              height: 32,
            ),
            anchorY: 12.0,
          ),
        ),
        topStartCap: TerrainMaterialCapSpec(
          region: TerrainMaterialImageRegionSpec(
            assetPath: 'terrain/tx_tileset_ground/atlas.png',
            x: 0,
            y: 0,
            width: 32,
            height: 32,
          ),
          anchorX: 0.0,
          anchorY: 12.0,
        ),
        topEndCap: TerrainMaterialCapSpec(
          region: TerrainMaterialImageRegionSpec(
            assetPath: 'terrain/tx_tileset_ground/atlas.png',
            x: 64,
            y: 0,
            width: 32,
            height: 32,
          ),
          anchorX: 32.0,
          anchorY: 12.0,
        ),
      ),
    };
