// Generated by tool/generate_chunk_runtime_data.dart.
// Do not edit by hand.

part of 'terrain_material_registry.dart';

const Map<String, TerrainMaterialSpec> _authoredTerrainMaterials =
    <String, TerrainMaterialSpec>{
      'grass_dirt': TerrainMaterialSpec(
        key: 'grass_dirt',
        displayName: 'Grass / Dirt',
        revision: 1,
        fillAssetPath: 'terrain/grass_dirt/fill.png',
        top: TerrainMaterialEdgeProfileSpec(
          base: TerrainMaterialEdgeLayerSpec(
            assetPath: 'terrain/grass_dirt/surface.png',
            anchorY: 12.0,
          ),
          detail: TerrainMaterialEdgeLayerSpec(
            assetPath: 'terrain/grass_dirt/foreground.png',
            anchorY: 0.0,
          ),
        ),
        topStartCap: TerrainMaterialCapSpec(
          assetPath: 'terrain/grass_dirt/cap_left.png',
          anchorX: 0.0,
          anchorY: 12.0,
        ),
        topEndCap: TerrainMaterialCapSpec(
          assetPath: 'terrain/grass_dirt/cap_right.png',
          anchorX: 128.0,
          anchorY: 12.0,
        ),
      ),
    };
