/// GENERATED FILE. DO NOT EDIT BY HAND.
///
/// Generated by tool/generate_chunk_runtime_data.dart from:
/// - assets/authoring/level/parallax_defs.json
library;

import '../components/pixel_parallax_backdrop.dart';
import 'parallax_theme.dart';

const ParallaxTheme authoredParallaxThemeField = ParallaxTheme(
  backgroundLayers: <PixelParallaxLayerSpec>[
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/layer_01.png',
      parallaxFactor: 0.1,
      opacity: 1,
      yOffset: -44,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/layer_02.png',
      parallaxFactor: 0.15,
      opacity: 1,
      yOffset: -44,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/layer_03.png',
      parallaxFactor: 0.2,
      opacity: 1,
      yOffset: -44,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/layer_04.png',
      parallaxFactor: 0.3,
      opacity: 1,
      yOffset: -44,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/layer_05.png',
      parallaxFactor: 0.4,
      opacity: 1,
      yOffset: -44,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/layer_06.png',
      parallaxFactor: 0.5,
      opacity: 1,
      yOffset: -44,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/layer_07.png',
      parallaxFactor: 0.6,
      opacity: 1,
      yOffset: -44,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/layer_08.png',
      parallaxFactor: 0.7,
      opacity: 1,
      yOffset: -44,
    ),
  ],
  foregroundLayers: <PixelParallaxLayerSpec>[
  ],
);

const ParallaxTheme authoredParallaxThemeForest = ParallaxTheme(
  backgroundLayers: <PixelParallaxLayerSpec>[
    PixelParallaxLayerSpec(
      assetPath: 'parallax/forest/layer_01.png',
      parallaxFactor: 0.1,
      opacity: 1,
      yOffset: -44,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/forest/layer_02.png',
      parallaxFactor: 0.2,
      opacity: 1,
      yOffset: -44,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/forest/layer_03.png',
      parallaxFactor: 0.3,
      opacity: 1,
      yOffset: -44,
    ),
  ],
  foregroundLayers: <PixelParallaxLayerSpec>[
  ],
);

const ParallaxTheme authoredParallaxThemeNewLevel = ParallaxTheme(
  backgroundLayers: <PixelParallaxLayerSpec>[
  ],
  foregroundLayers: <PixelParallaxLayerSpec>[
  ],
);

const Map<String, ParallaxTheme> authoredParallaxThemesById = <String, ParallaxTheme>{
  'field': authoredParallaxThemeField,
  'forest': authoredParallaxThemeForest,
  'new_level': authoredParallaxThemeNewLevel,
};
