/// GENERATED FILE. DO NOT EDIT BY HAND.
///
/// Generated by tool/generate_chunk_runtime_data.dart from:
/// - assets/authoring/level/parallax_defs.json
library;

import '../components/pixel_parallax_backdrop.dart';
import 'parallax_theme.dart';

const ParallaxTheme authoredParallaxThemeField = ParallaxTheme(
  backgroundLayers: <PixelParallaxLayerSpec>[
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/Field Layer 01.png',
      parallaxFactor: 0.1,
      opacity: 1,
      yOffset: 0,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/Field Layer 02.png',
      parallaxFactor: 0.15,
      opacity: 1,
      yOffset: 0,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/Field Layer 03.png',
      parallaxFactor: 0.2,
      opacity: 1,
      yOffset: 0,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/Field Layer 04.png',
      parallaxFactor: 0.3,
      opacity: 1,
      yOffset: 0,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/Field Layer 05.png',
      parallaxFactor: 0.4,
      opacity: 1,
      yOffset: 0,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/Field Layer 06.png',
      parallaxFactor: 0.5,
      opacity: 1,
      yOffset: 0,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/Field Layer 07.png',
      parallaxFactor: 0.6,
      opacity: 1,
      yOffset: 0,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/Field Layer 08.png',
      parallaxFactor: 0.7,
      opacity: 1,
      yOffset: 0,
    ),
  ],
  groundMaterialAssetPath: 'parallax/field/Field Layer 09.png',
  foregroundLayers: <PixelParallaxLayerSpec>[
    PixelParallaxLayerSpec(
      assetPath: 'parallax/field/Field Layer 10.png',
      parallaxFactor: 1,
      opacity: 1,
      yOffset: 0,
    ),
  ],
);

const ParallaxTheme authoredParallaxThemeForest = ParallaxTheme(
  backgroundLayers: <PixelParallaxLayerSpec>[
    PixelParallaxLayerSpec(
      assetPath: 'parallax/forest/Forest Layer 01.png',
      parallaxFactor: 0.1,
      opacity: 1,
      yOffset: 0,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/forest/Forest Layer 02.png',
      parallaxFactor: 0.2,
      opacity: 1,
      yOffset: 0,
    ),
    PixelParallaxLayerSpec(
      assetPath: 'parallax/forest/Forest Layer 03.png',
      parallaxFactor: 0.3,
      opacity: 1,
      yOffset: 0,
    ),
  ],
  groundMaterialAssetPath: 'parallax/forest/Forest Layer 04.png',
  foregroundLayers: <PixelParallaxLayerSpec>[
  ],
);

const Map<String, ParallaxTheme> authoredParallaxThemesById = <String, ParallaxTheme>{
  'field': authoredParallaxThemeField,
  'forest': authoredParallaxThemeForest,
};
