import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:runner_core/collision/terrain/terrain_authoring_issue.dart';
import 'package:runner_core/collision/terrain/terrain_authoring_seam_signature.dart';
import 'package:runner_core/track/staged_terrain_data.dart';

import '../fixtures/polygon_terrain_generator/staged_authored_terrain.g.dart'
    as golden;
import '../../tool/generated_artifact_plan.dart';
import '../../tool/polygon_terrain_artifact_validation.dart';
import '../../tool/polygon_terrain_compilation.dart';
import '../../tool/polygon_terrain_render.dart';
import '../../tool/polygon_terrain_seam_manifest.dart';
import '../../tool/polygon_terrain_seam_validation.dart';
import '../../tool/polygon_terrain_source.dart';

const String _fixtureDirectory = 'test/fixtures/polygon_terrain_generator';
const String _goldenPath = '$_fixtureDirectory/staged_authored_terrain.g.dart';
const String _chunkSourcePath = 'chunks/forest/fixture_chunk.json';

void main() {
  test(
    'staged Dart render is exact, local, and drift-plan compatible',
    () async {
      final first = buildStagedPolygonTerrainArtifact(
        batch: _validated(<PolygonTerrainCompiledChunk>[_compileFixture()]),
        outputPath: _goldenPath,
      );
      final second = buildStagedPolygonTerrainArtifact(
        batch: _validated(<PolygonTerrainCompiledChunk>[_compileFixture()]),
        outputPath: _goldenPath,
      );

      if (Platform.environment['UPDATE_POLYGON_TERRAIN_GOLDEN'] == '1') {
        await GeneratedArtifactPlan(<GeneratedArtifact>[first]).writeAll();
      }

      expect(second.content, first.content);
      expect(first.content, File(_goldenPath).readAsStringSync());
      expect(
        await GeneratedArtifactPlan(<GeneratedArtifact>[first]).inspectDrift(),
        isEmpty,
      );
      expect(first.content, isNot(contains('chunkIndex')));
      expect(first.content, contains('formatVersion: 3'));
      expect(first.content, contains('compilerGeometryVersion: 1'));
      expect(
        first.content,
        contains('authoringPolygonSignatureFormat: "authoring-polygons-v1"'),
      );
      expect(
        first.content,
        contains('authoringSeamSignatureFormat: "authoring-seams-v1"'),
      );
      expect(
        first.content,
        contains(
          'authoringSeamSignature: '
          '"c11c965911bb3990c762fc8babb016240b06309c1ecaf7c39b8007b8049f08ab"',
        ),
      );
      expect(first.content, contains('sourceSignatureFormat: "source-v1"'));
      expect(first.content, contains('edgeSignatureFormat: "edges-v1"'));
      expect(
        first.content,
        contains('placementSignatureFormat: "authoring-placement-v1"'),
      );
      expect(
        first.content,
        contains('triangleSignatureFormat: "authoring-triangles-v1"'),
      );
      expect(golden.stagedAuthoredTerrain.chunks, hasLength(1));
      expect(golden.stagedAuthoredTerrain.chunks.single.polygons, hasLength(3));
      expect(golden.stagedAuthoredTerrain.chunks.single.edges, hasLength(13));
      expect(
        golden.stagedAuthoredTerrain.chunks.single.triangles,
        hasLength(10),
      );
    },
  );

  test('staged Dart render sorts chunk input explicitly', () {
    final earlier = _compileFixture(chunkKey: 'a_fixture');
    final later = _compileFixture(chunkKey: 'z_fixture');

    expect(
      renderStagedPolygonTerrainDart(
        _validated(<PolygonTerrainCompiledChunk>[later, earlier]),
      ),
      renderStagedPolygonTerrainDart(
        _validated(<PolygonTerrainCompiledChunk>[earlier, later]),
      ),
    );
  });

  test(
    'staged output gate accepts matching signatures and exact bytes',
    () async {
      final expected = _validated(<PolygonTerrainCompiledChunk>[
        _compileFixture(),
      ]);
      final output = buildStagedPolygonTerrainArtifact(
        batch: expected,
        outputPath: _goldenPath,
      );
      final result = await validateStagedPolygonTerrainOutput(
        expected: expected,
        artifact: golden.stagedAuthoredTerrain,
        outputPlan: GeneratedArtifactPlan(<GeneratedArtifact>[output]),
        sourcePath: _goldenPath,
      );

      expect(result.issues, isEmpty);
      expect(result.artifact, same(golden.stagedAuthoredTerrain));
    },
  );

  test('staged output gate normalizes generated byte drift', () async {
    final root = Directory.systemTemp.createTempSync('terrain_output_gate_');
    addTearDown(() => root.deleteSync(recursive: true));
    final outputPath = '${root.path}${Platform.pathSeparator}staged.dart';
    final expected = _validated(<PolygonTerrainCompiledChunk>[
      _compileFixture(),
    ]);
    final output = buildStagedPolygonTerrainArtifact(
      batch: expected,
      outputPath: outputPath,
    );

    final result = await validateStagedPolygonTerrainOutput(
      expected: expected,
      artifact: golden.stagedAuthoredTerrain,
      outputPlan: GeneratedArtifactPlan(<GeneratedArtifact>[output]),
      sourcePath: _goldenPath,
    );

    expect(result.artifact, isNull);
    expect(result.issues, hasLength(1));
    final issue = result.issues.single;
    expect(issue.severity, TerrainAuthoringIssueSeverity.error);
    expect(issue.code, 'generated_output_missing');
    expect(issue.sourcePath, _displayPath(outputPath));
    expect(issue.ownerKey, _displayPath(outputPath));
    expect(issue.placementKey, isNull);
    expect(issue.shapeId, isNull);
    expect(issue.elementIndex, isNull);
  });

  test('typed staged artifact rejects every stale per-chunk signature', () {
    final expected = _validated(<PolygonTerrainCompiledChunk>[
      _compileFixture(),
    ]);
    final source = golden.stagedAuthoredTerrain.chunks.single;
    final cases =
        <(String, StagedTerrainChunkData Function(StagedTerrainChunkData))>[
          (
            'authoring_polygon_signature_mismatch',
            (chunk) =>
                _copyChunk(chunk, authoringPolygonSignature: 'stale-authoring'),
          ),
          (
            'source_signature_mismatch',
            (chunk) => _copyChunk(chunk, sourceSignature: 'stale-source'),
          ),
          (
            'edge_signature_mismatch',
            (chunk) => _copyChunk(chunk, edgeSignature: 'stale-edge'),
          ),
          (
            'placement_signature_mismatch',
            (chunk) => _copyChunk(chunk, placementSignature: 'stale-placement'),
          ),
          (
            'triangle_signature_mismatch',
            (chunk) => _copyChunk(chunk, triangleSignature: 'stale-triangle'),
          ),
        ];

    for (final entry in cases) {
      final result = validateStagedPolygonTerrainArtifact(
        expected: expected,
        artifact: _copyArtifact(
          golden.stagedAuthoredTerrain,
          chunks: <StagedTerrainChunkData>[entry.$2(source)],
        ),
        sourcePath: _goldenPath,
      );

      expect(result.artifact, isNull, reason: entry.$1);
      expect(result.issues, hasLength(1), reason: entry.$1);
      final issue = result.issues.single;
      expect(issue.severity, TerrainAuthoringIssueSeverity.error);
      expect(issue.code, entry.$1);
      expect(issue.sourcePath, _goldenPath);
      expect(issue.ownerKey, 'fixture_chunk');
      expect(issue.placementKey, isNull);
      expect(issue.shapeId, isNull);
      expect(issue.elementIndex, isNull);
      expect(issue.message, contains('expected'));
      expect(issue.message, contains('found'));
    }
  });

  test('typed staged artifact rejects version and signature format drift', () {
    final expected = _validated(<PolygonTerrainCompiledChunk>[
      _compileFixture(),
    ]);
    final source = golden.stagedAuthoredTerrain;
    final cases =
        <
          (
            String,
            StagedTerrainArtifactData Function(StagedTerrainArtifactData),
          )
        >[
          (
            'staged_artifact_format_mismatch',
            (artifact) => _copyArtifact(
              artifact,
              chunks: artifact.chunks,
              formatVersion: 99,
            ),
          ),
          (
            'staged_compiler_geometry_version_mismatch',
            (artifact) => _copyArtifact(
              artifact,
              chunks: artifact.chunks,
              compilerGeometryVersion: 99,
            ),
          ),
          (
            'authoring_polygon_signature_format_mismatch',
            (artifact) => _copyArtifact(
              artifact,
              chunks: artifact.chunks,
              authoringPolygonSignatureFormat: 'stale-authoring-format',
            ),
          ),
          (
            'authoring_seam_signature_format_mismatch',
            (artifact) => _copyArtifact(
              artifact,
              chunks: artifact.chunks,
              authoringSeamSignatureFormat: 'stale-seam-format',
            ),
          ),
          (
            'authoring_seam_signature_mismatch',
            (artifact) => _copyArtifact(
              artifact,
              chunks: artifact.chunks,
              authoringSeamSignature: 'stale-seam',
            ),
          ),
          (
            'source_signature_format_mismatch',
            (artifact) => _copyArtifact(
              artifact,
              chunks: artifact.chunks,
              sourceSignatureFormat: 'stale-source-format',
            ),
          ),
          (
            'edge_signature_format_mismatch',
            (artifact) => _copyArtifact(
              artifact,
              chunks: artifact.chunks,
              edgeSignatureFormat: 'stale-edge-format',
            ),
          ),
          (
            'placement_signature_format_mismatch',
            (artifact) => _copyArtifact(
              artifact,
              chunks: artifact.chunks,
              placementSignatureFormat: 'stale-placement-format',
            ),
          ),
          (
            'triangle_signature_format_mismatch',
            (artifact) => _copyArtifact(
              artifact,
              chunks: artifact.chunks,
              triangleSignatureFormat: 'stale-triangle-format',
            ),
          ),
        ];

    for (final entry in cases) {
      final result = validateStagedPolygonTerrainArtifact(
        expected: expected,
        artifact: entry.$2(source),
        sourcePath: _goldenPath,
      );

      expect(result.artifact, isNull, reason: entry.$1);
      expect(result.issues.map((issue) => issue.code), <String>[
        entry.$1,
      ], reason: entry.$1);
      expect(result.issues.single.ownerKey, _goldenPath);
    }
  });

  test('typed staged artifact rejects chunk-set and metadata drift', () {
    final expected = _validated(<PolygonTerrainCompiledChunk>[
      _compileFixture(),
    ]);
    final source = golden.stagedAuthoredTerrain;
    final chunk = source.chunks.single;
    final cases = <(String, StagedTerrainArtifactData)>[
      (
        'staged_artifact_chunk_missing',
        _copyArtifact(source, chunks: const <StagedTerrainChunkData>[]),
      ),
      (
        'staged_artifact_chunk_duplicate',
        _copyArtifact(source, chunks: <StagedTerrainChunkData>[chunk, chunk]),
      ),
      (
        'staged_chunk_metadata_mismatch',
        _copyArtifact(
          source,
          chunks: <StagedTerrainChunkData>[
            _copyChunk(chunk, revision: chunk.revision + 1),
          ],
        ),
      ),
    ];

    for (final entry in cases) {
      final result = validateStagedPolygonTerrainArtifact(
        expected: expected,
        artifact: entry.$2,
        sourcePath: _goldenPath,
      );

      expect(result.artifact, isNull, reason: entry.$1);
      expect(result.issues.map((issue) => issue.code), <String>[
        entry.$1,
      ], reason: entry.$1);
      expect(result.issues.single.ownerKey, 'fixture_chunk');
    }
  });

  test('validated render boundary rejects empty and duplicate chunk sets', () {
    final compiled = _compileFixture();

    expect(
      () => renderStagedPolygonTerrainDart(
        _validated(const <PolygonTerrainCompiledChunk>[]),
      ),
      throwsArgumentError,
    );
    final duplicate = validatePolygonTerrainSeams(
      chunks: <PolygonTerrainCompiledChunk>[compiled, compiled],
      manifest: _emptySeamManifest(),
    );
    expect(duplicate.batch, isNull);
    expect(duplicate.issues.map((issue) => issue.code), <String>[
      'staged_seam_chunk_duplicate',
    ]);
  });

  test('staged records remain unreachable from production construction', () {
    const productionRoots = <String>[
      'packages/runner_core/lib',
      'lib',
      'services/replay_validator/lib',
    ];
    final imports = <String>[];
    for (final rootPath in productionRoots) {
      for (final entity in Directory(rootPath).listSync(recursive: true)) {
        if (entity is! File || !entity.path.endsWith('.dart')) continue;
        final normalizedPath = entity.path.replaceAll('\\', '/');
        if (normalizedPath.contains('/track/staged_')) {
          continue;
        }
        final source = entity.readAsStringSync();
        if (source.contains('staged_terrain_data.dart') ||
            source.contains('staged_authored_terrain.dart')) {
          imports.add(entity.path.replaceAll('\\', '/'));
        }
      }
    }

    expect(imports, isEmpty);
    final liveGenerator = File(
      'tool/generate_chunk_runtime_data.dart',
    ).readAsStringSync();
    expect(liveGenerator, contains('polygon_terrain_render.dart'));
    expect(liveGenerator, contains('buildStagedPolygonTerrainArtifact'));
    expect(liveGenerator, isNot(contains('staged_authored_terrain.dart')));
  });
}

PolygonTerrainValidatedBatch _validated(
  Iterable<PolygonTerrainCompiledChunk> chunks,
) {
  final result = validatePolygonTerrainSeams(
    chunks: chunks,
    manifest: _emptySeamManifest(),
  );
  expect(result.issues, isEmpty);
  return result.batch!;
}

PolygonTerrainSeamManifest _emptySeamManifest() => PolygonTerrainSeamManifest(
  signature: TerrainAuthoringSeamSignature(const []),
  sourcePath: 'fixture:isolated-compiler',
);

PolygonTerrainCompiledChunk _compileFixture({String? chunkKey}) {
  final prefabs = decodePolygonTerrainPrefabs(
    File('$_fixtureDirectory/prefab_defs.json').readAsStringSync(),
    sourcePath: 'prefab_defs.json',
  );
  final rawChunk = File('$_fixtureDirectory/chunk.json').readAsStringSync();
  final resolvedChunkKey = chunkKey ?? 'fixture_chunk';
  final chunkJson = jsonDecode(rawChunk) as Map<String, Object?>;
  chunkJson['chunkKey'] = resolvedChunkKey;
  chunkJson['id'] = resolvedChunkKey;
  final sourcePath = chunkKey == null
      ? _chunkSourcePath
      : 'chunks/forest/$resolvedChunkKey.json';
  final chunk = decodePolygonTerrainChunk(
    jsonEncode(chunkJson),
    sourcePath: sourcePath,
  );
  final result = compilePolygonTerrainChunk(
    chunk: chunk,
    prefabSources: prefabs,
    sourcePath: sourcePath,
  );
  expect(result.issues, isEmpty);
  return result.compiled!;
}

StagedTerrainArtifactData _copyArtifact(
  StagedTerrainArtifactData source, {
  required Iterable<StagedTerrainChunkData> chunks,
  int? formatVersion,
  int? compilerGeometryVersion,
  String? authoringPolygonSignatureFormat,
  String? authoringSeamSignatureFormat,
  String? authoringSeamSignature,
  String? sourceSignatureFormat,
  String? edgeSignatureFormat,
  String? placementSignatureFormat,
  String? triangleSignatureFormat,
}) => StagedTerrainArtifactData(
  formatVersion: formatVersion ?? source.formatVersion,
  compilerGeometryVersion:
      compilerGeometryVersion ?? source.compilerGeometryVersion,
  authoringPolygonSignatureFormat:
      authoringPolygonSignatureFormat ?? source.authoringPolygonSignatureFormat,
  authoringSeamSignatureFormat:
      authoringSeamSignatureFormat ?? source.authoringSeamSignatureFormat,
  authoringSeamSignature:
      authoringSeamSignature ?? source.authoringSeamSignature,
  sourceSignatureFormat: sourceSignatureFormat ?? source.sourceSignatureFormat,
  edgeSignatureFormat: edgeSignatureFormat ?? source.edgeSignatureFormat,
  placementSignatureFormat:
      placementSignatureFormat ?? source.placementSignatureFormat,
  triangleSignatureFormat:
      triangleSignatureFormat ?? source.triangleSignatureFormat,
  chunks: chunks,
);

StagedTerrainChunkData _copyChunk(
  StagedTerrainChunkData source, {
  int? revision,
  String? authoringPolygonSignature,
  String? sourceSignature,
  String? edgeSignature,
  String? placementSignature,
  String? triangleSignature,
}) => StagedTerrainChunkData(
  chunkKey: source.chunkKey,
  id: source.id,
  revision: revision ?? source.revision,
  status: source.status,
  levelId: source.levelId,
  tileSize: source.tileSize,
  width: source.width,
  height: source.height,
  difficulty: source.difficulty,
  assemblyGroupId: source.assemblyGroupId,
  authoringPolygonSignature:
      authoringPolygonSignature ?? source.authoringPolygonSignature,
  sourceSignature: sourceSignature ?? source.sourceSignature,
  edgeSignature: edgeSignature ?? source.edgeSignature,
  placementSignature: placementSignature ?? source.placementSignature,
  triangleSignature: triangleSignature ?? source.triangleSignature,
  polygons: source.polygons,
  edges: source.edges,
  triangles: source.triangles,
  placementLineage: source.placementLineage,
);

String _displayPath(String path) => path.replaceAll('\\', '/');
