/// GENERATED FILE. DO NOT EDIT BY HAND.
///
/// Generated by tool/generate_chunk_runtime_data.dart from:
/// - `assets/authoring/level/chunks/<levelId>/**/*.json`
/// - assets/authoring/level/prefab_defs.json
/// - assets/authoring/level/tile_defs.json
library;

import 'chunk_pattern.dart';
import 'chunk_pattern_source.dart';

const List<ChunkPattern> fieldEarlyPatterns = <ChunkPattern>[
];

const List<ChunkPattern> fieldEasyPatterns = <ChunkPattern>[
];

const List<ChunkPattern> fieldNormalPatterns = <ChunkPattern>[
  ChunkPattern(
    name: 'field_flat',
    chunkKey: 'field_flat',
    assemblyGroupId: 'default',
    visualSprites: <ChunkVisualSpriteRel>[
    ],
    spawnMarkers: <SpawnMarker>[
    ],
  ),
];

const List<ChunkPattern> fieldHardPatterns = <ChunkPattern>[
];

const List<ChunkPattern> forestEarlyPatterns = <ChunkPattern>[
  ChunkPattern(
    name: 'forest_early_flat',
    chunkKey: 'forest_earlt_flat',
    assemblyGroupId: 'default',
    visualSprites: <ChunkVisualSpriteRel>[
    ],
    spawnMarkers: <SpawnMarker>[
    ],
  ),
];

const List<ChunkPattern> forestEasyPatterns = <ChunkPattern>[
];

const List<ChunkPattern> forestNormalPatterns = <ChunkPattern>[
];

const List<ChunkPattern> forestHardPatterns = <ChunkPattern>[
];

const List<ChunkPattern> newLevelEarlyPatterns = <ChunkPattern>[
];

const List<ChunkPattern> newLevelEasyPatterns = <ChunkPattern>[
];

const List<ChunkPattern> newLevelNormalPatterns = <ChunkPattern>[
  ChunkPattern(
    name: 'new_level_flat',
    chunkKey: 'new_level_flat',
    assemblyGroupId: 'default',
    visualSprites: <ChunkVisualSpriteRel>[
    ],
    spawnMarkers: <SpawnMarker>[
    ],
  ),
];

const List<ChunkPattern> newLevelHardPatterns = <ChunkPattern>[
];

const Map<String, ChunkPatternListSource> authoredChunkPatternSourcesByLevel = <String, ChunkPatternListSource>{
  'field': ChunkPatternListSource(
    earlyPatterns: fieldEarlyPatterns,
    easyPatterns: fieldEasyPatterns,
    normalPatterns: fieldNormalPatterns,
    hardPatterns: fieldHardPatterns,
  ),
  'forest': ChunkPatternListSource(
    earlyPatterns: forestEarlyPatterns,
    easyPatterns: forestEasyPatterns,
    normalPatterns: forestNormalPatterns,
    hardPatterns: forestHardPatterns,
  ),
  'new_level': ChunkPatternListSource(
    earlyPatterns: newLevelEarlyPatterns,
    easyPatterns: newLevelEasyPatterns,
    normalPatterns: newLevelNormalPatterns,
    hardPatterns: newLevelHardPatterns,
  ),
};

ChunkPatternListSource authoredChunkPatternSourceForLevel(
  String levelId,
) {
  final source = authoredChunkPatternSourcesByLevel[levelId];
  if (source != null) {
    return source;
  }
  throw StateError('No authored chunk pattern source for levelId="$levelId".');
}
