/// GENERATED FILE. DO NOT EDIT BY HAND.
///
/// Generated by tool/generate_chunk_runtime_data.dart from canonical prefab-v3/chunk-v2
/// polygon source. This staged artifact is not runtime authority.
library;

import 'package:runner_core/track/staged_terrain_data.dart';

final StagedTerrainArtifactData stagedAuthoredTerrain = StagedTerrainArtifactData(
  formatVersion: 3,
  compilerGeometryVersion: 1,
  authoringPolygonSignatureFormat: "authoring-polygons-v1",
  authoringSeamSignatureFormat: "authoring-seams-v1",
  authoringSeamSignature: "7878b7f1898fa5040d04cea74be10e5b46f8e8e552b598340d09e24708adbdf3",
  sourceSignatureFormat: "source-v1",
  edgeSignatureFormat: "edges-v1",
  placementSignatureFormat: "authoring-placement-v1",
  triangleSignatureFormat: "authoring-triangles-v1",
  chunks: <StagedTerrainChunkData>[
    StagedTerrainChunkData(
      chunkKey: "field_flat",
      id: "field_flat",
      revision: 10,
      status: "active",
      levelId: "field",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "normal",
      assemblyGroupId: "default",
      authoringPolygonSignature: "13a98be93fab60e24e7dce75bc151e5babfad2d76751ebee4ef9df2b09d1604a",
      sourceSignature: "3e3582da4a7bbe189aba0552f142c71a231e4a016f2c4a32760b4b37202d0b2d",
      edgeSignature: "df9567881f9e6fd6be39aca9128614c00882f14ac17647d70e70aed554a72548",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "61be454042b691983fb700c94d404d9fe01bc80e50653fcfb09ff1004ac0ca49",
      polygons: <StagedTerrainPolygonData>[
        StagedTerrainPolygonData(
          sourcePath: "assets/authoring/level/chunks/field/field_flat.json#direct=solid_001",
          id: StagedTerrainSourceId(
            chunkKey: "field_flat",
            placementKey: null,
            shapeId: "solid_001",
          ),
          sourceVertices: <StagedTerrainPoint>[
            StagedTerrainPoint(96, 352),
            StagedTerrainPoint(1056, 352),
            StagedTerrainPoint(1056, 448),
            StagedTerrainPoint(96, 448),
          ],
          vertices: <StagedTerrainPoint>[
            StagedTerrainPoint(49152, 180224),
            StagedTerrainPoint(540672, 180224),
            StagedTerrainPoint(540672, 229376),
            StagedTerrainPoint(49152, 229376),
          ],
          collisionMode: StagedTerrainCollisionMode.solid,
          surfaceKind: null,
          materialKey: null,
        ),
      ],
      edges: <StagedTerrainEdgeData>[
        StagedTerrainEdgeData(
          id: StagedTerrainEdgeId(
            sourceId: StagedTerrainSourceId(
              chunkKey: "field_flat",
              placementKey: null,
              shapeId: "solid_001",
            ),
            localEdgeIndex: 0,
            subEdgeIndex: 0,
          ),
          start: StagedTerrainPoint(49152, 180224),
          end: StagedTerrainPoint(540672, 180224),
          tangent: StagedTerrainPoint(1024, 0),
          outwardNormal: StagedTerrainPoint(0, -1024),
          collisionMode: StagedTerrainCollisionMode.solid,
          surfaceKind: null,
          materialKey: null,
          previousId: StagedTerrainEdgeId(
            sourceId: StagedTerrainSourceId(
              chunkKey: "field_flat",
              placementKey: null,
              shapeId: "solid_001",
            ),
            localEdgeIndex: 3,
            subEdgeIndex: 0,
          ),
          nextId: StagedTerrainEdgeId(
            sourceId: StagedTerrainSourceId(
              chunkKey: "field_flat",
              placementKey: null,
              shapeId: "solid_001",
            ),
            localEdgeIndex: 1,
            subEdgeIndex: 0,
          ),
          startJoin: StagedTerrainVertexJoin.connected,
          endJoin: StagedTerrainVertexJoin.connected,
        ),
        StagedTerrainEdgeData(
          id: StagedTerrainEdgeId(
            sourceId: StagedTerrainSourceId(
              chunkKey: "field_flat",
              placementKey: null,
              shapeId: "solid_001",
            ),
            localEdgeIndex: 1,
            subEdgeIndex: 0,
          ),
          start: StagedTerrainPoint(540672, 180224),
          end: StagedTerrainPoint(540672, 229376),
          tangent: StagedTerrainPoint(0, 1024),
          outwardNormal: StagedTerrainPoint(1024, 0),
          collisionMode: StagedTerrainCollisionMode.solid,
          surfaceKind: null,
          materialKey: null,
          previousId: StagedTerrainEdgeId(
            sourceId: StagedTerrainSourceId(
              chunkKey: "field_flat",
              placementKey: null,
              shapeId: "solid_001",
            ),
            localEdgeIndex: 0,
            subEdgeIndex: 0,
          ),
          nextId: StagedTerrainEdgeId(
            sourceId: StagedTerrainSourceId(
              chunkKey: "field_flat",
              placementKey: null,
              shapeId: "solid_001",
            ),
            localEdgeIndex: 2,
            subEdgeIndex: 0,
          ),
          startJoin: StagedTerrainVertexJoin.connected,
          endJoin: StagedTerrainVertexJoin.connected,
        ),
        StagedTerrainEdgeData(
          id: StagedTerrainEdgeId(
            sourceId: StagedTerrainSourceId(
              chunkKey: "field_flat",
              placementKey: null,
              shapeId: "solid_001",
            ),
            localEdgeIndex: 2,
            subEdgeIndex: 0,
          ),
          start: StagedTerrainPoint(540672, 229376),
          end: StagedTerrainPoint(49152, 229376),
          tangent: StagedTerrainPoint(-1024, 0),
          outwardNormal: StagedTerrainPoint(0, 1024),
          collisionMode: StagedTerrainCollisionMode.solid,
          surfaceKind: null,
          materialKey: null,
          previousId: StagedTerrainEdgeId(
            sourceId: StagedTerrainSourceId(
              chunkKey: "field_flat",
              placementKey: null,
              shapeId: "solid_001",
            ),
            localEdgeIndex: 1,
            subEdgeIndex: 0,
          ),
          nextId: StagedTerrainEdgeId(
            sourceId: StagedTerrainSourceId(
              chunkKey: "field_flat",
              placementKey: null,
              shapeId: "solid_001",
            ),
            localEdgeIndex: 3,
            subEdgeIndex: 0,
          ),
          startJoin: StagedTerrainVertexJoin.connected,
          endJoin: StagedTerrainVertexJoin.connected,
        ),
        StagedTerrainEdgeData(
          id: StagedTerrainEdgeId(
            sourceId: StagedTerrainSourceId(
              chunkKey: "field_flat",
              placementKey: null,
              shapeId: "solid_001",
            ),
            localEdgeIndex: 3,
            subEdgeIndex: 0,
          ),
          start: StagedTerrainPoint(49152, 229376),
          end: StagedTerrainPoint(49152, 180224),
          tangent: StagedTerrainPoint(0, -1024),
          outwardNormal: StagedTerrainPoint(-1024, 0),
          collisionMode: StagedTerrainCollisionMode.solid,
          surfaceKind: null,
          materialKey: null,
          previousId: StagedTerrainEdgeId(
            sourceId: StagedTerrainSourceId(
              chunkKey: "field_flat",
              placementKey: null,
              shapeId: "solid_001",
            ),
            localEdgeIndex: 2,
            subEdgeIndex: 0,
          ),
          nextId: StagedTerrainEdgeId(
            sourceId: StagedTerrainSourceId(
              chunkKey: "field_flat",
              placementKey: null,
              shapeId: "solid_001",
            ),
            localEdgeIndex: 0,
            subEdgeIndex: 0,
          ),
          startJoin: StagedTerrainVertexJoin.connected,
          endJoin: StagedTerrainVertexJoin.connected,
        ),
      ],
      triangles: <StagedTerrainTriangleData>[
        StagedTerrainTriangleData(
          sourceId: StagedTerrainSourceId(
            chunkKey: "field_flat",
            placementKey: null,
            shapeId: "solid_001",
          ),
          first: 1,
          second: 2,
          third: 3,
        ),
        StagedTerrainTriangleData(
          sourceId: StagedTerrainSourceId(
            chunkKey: "field_flat",
            placementKey: null,
            shapeId: "solid_001",
          ),
          first: 3,
          second: 0,
          third: 1,
        ),
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_earlt_flat",
      id: "forest_early_flat",
      revision: 3,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "early",
      assemblyGroupId: "default",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_early_00",
      id: "forest_early_00",
      revision: 516,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "early",
      assemblyGroupId: "default",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_early_01",
      id: "forest_early_01",
      revision: 765,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "early",
      assemblyGroupId: "default",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_early_02",
      id: "forest_early_02",
      revision: 401,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "early",
      assemblyGroupId: "default",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_early_03",
      id: "forest_early_03",
      revision: 656,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "early",
      assemblyGroupId: "default",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_easy_woodcamp_00",
      id: "forest_easy_woodcamp_00",
      revision: 328,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "easy",
      assemblyGroupId: "woodcamp",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_easy_woodcamp_00_2",
      id: "forest_normal_woodcamp_00",
      revision: 7,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "normal",
      assemblyGroupId: "default",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
  ],
);
