/// GENERATED FILE. DO NOT EDIT BY HAND.
///
/// Generated by tool/generate_chunk_runtime_data.dart from canonical prefab-v3/chunk-v2
/// polygon source. This staged artifact is not runtime authority.
library;

import 'package:runner_core/track/staged_terrain_data.dart';

final StagedTerrainArtifactData stagedAuthoredTerrain = StagedTerrainArtifactData(
  formatVersion: 3,
  compilerGeometryVersion: 1,
  authoringPolygonSignatureFormat: "authoring-polygons-v1",
  authoringSeamSignatureFormat: "authoring-seams-v1",
  authoringSeamSignature: "7878b7f1898fa5040d04cea74be10e5b46f8e8e552b598340d09e24708adbdf3",
  sourceSignatureFormat: "source-v1",
  edgeSignatureFormat: "edges-v1",
  placementSignatureFormat: "authoring-placement-v1",
  triangleSignatureFormat: "authoring-triangles-v1",
  chunks: <StagedTerrainChunkData>[
    StagedTerrainChunkData(
      chunkKey: "field_flat",
      id: "field_flat",
      revision: 2,
      status: "active",
      levelId: "field",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "normal",
      assemblyGroupId: "default",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_earlt_flat",
      id: "forest_early_flat",
      revision: 3,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "early",
      assemblyGroupId: "default",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_early_00",
      id: "forest_early_00",
      revision: 516,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "early",
      assemblyGroupId: "default",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_early_01",
      id: "forest_early_01",
      revision: 765,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "early",
      assemblyGroupId: "default",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_early_02",
      id: "forest_early_02",
      revision: 401,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "early",
      assemblyGroupId: "default",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_early_03",
      id: "forest_early_03",
      revision: 656,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "early",
      assemblyGroupId: "default",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_easy_woodcamp_00",
      id: "forest_easy_woodcamp_00",
      revision: 328,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "easy",
      assemblyGroupId: "woodcamp",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
    StagedTerrainChunkData(
      chunkKey: "forest_easy_woodcamp_00_2",
      id: "forest_normal_woodcamp_00",
      revision: 7,
      status: "active",
      levelId: "forest",
      tileSize: 16,
      width: 600,
      height: 270,
      difficulty: "normal",
      assemblyGroupId: "default",
      authoringPolygonSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      sourceSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      edgeSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      placementSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      triangleSignature: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      polygons: <StagedTerrainPolygonData>[
      ],
      edges: <StagedTerrainEdgeData>[
      ],
      triangles: <StagedTerrainTriangleData>[
      ],
      placementLineage: <StagedTerrainPlacementLineageData>[
      ],
    ),
  ],
);
