// Generated by tools/combat/generate_projectile_profiles.py; do not edit.
import '../projectiles/projectile_id.dart';
import '../snapshots/enums.dart';
import 'combat_geometry.dart';

/// Opaque flight silhouettes, relative to the render anchor at runtime scale.
abstract final class ProjectilePoseCatalog {
  static List<CombatCapsule> frame(ProjectileId id, AnimKey anim, int frame) {
    final frames = switch ((id, anim)) {
      (ProjectileId.iceBolt, AnimKey.spawn) => _iceBoltSpawn,
      (ProjectileId.iceBolt, AnimKey.idle) => _iceBoltIdle,
      (ProjectileId.fireBolt, AnimKey.spawn) => _fireBoltSpawn,
      (ProjectileId.fireBolt, AnimKey.idle) => _fireBoltIdle,
      (ProjectileId.acidBolt, AnimKey.spawn) => _acidBoltSpawn,
      (ProjectileId.acidBolt, AnimKey.idle) => _acidBoltIdle,
      (ProjectileId.darkBolt, AnimKey.spawn) => _darkBoltSpawn,
      (ProjectileId.darkBolt, AnimKey.idle) => _darkBoltIdle,
      (ProjectileId.earthBolt, AnimKey.spawn) => _earthBoltSpawn,
      (ProjectileId.earthBolt, AnimKey.idle) => _earthBoltIdle,
      (ProjectileId.holyBolt, AnimKey.spawn) => _holyBoltSpawn,
      (ProjectileId.holyBolt, AnimKey.idle) => _holyBoltIdle,
      (ProjectileId.waterBolt, AnimKey.spawn) => _waterBoltSpawn,
      (ProjectileId.waterBolt, AnimKey.idle) => _waterBoltIdle,
      (ProjectileId.thunderBolt, AnimKey.spawn) => _thunderBoltSpawn,
      (ProjectileId.thunderBolt, AnimKey.idle) => _thunderBoltIdle,
      (ProjectileId.npcSpear, AnimKey.idle) => _npcSpearIdle,
      (ProjectileId.npcArrow, AnimKey.idle) => _npcArrowIdle,
      (ProjectileId.goddessOrb, AnimKey.spawn) => _goddessOrbSpawn,
      (ProjectileId.goddessOrb, AnimKey.idle) => _goddessOrbIdle,
      (ProjectileId.shoggothOrb, AnimKey.idle) => _shoggothOrbIdle,
      (ProjectileId.voidClaw, AnimKey.spawn) => _voidClawSpawn,
      (ProjectileId.voidClaw, AnimKey.idle) => _voidClawIdle,
      _ => const <List<CombatCapsule>>[],
    };
    return frames.isEmpty ? const [] : frames[frame % frames.length];
  }

  static const _iceBoltSpawn = [
    [CombatCapsule(-10.5, 0.5, -4.5, 0.5, 3.5)],
    [CombatCapsule(-9.5, 0.5, -0.5, 0.5, 4.5)],
    [CombatCapsule(-9.5, 0.5, 0.5, 0.5, 4.5)],
  ];
  static const _iceBoltIdle = [
    [CombatCapsule(-9.5, 0.5, 6.5, 0.5, 4.5)],
    [CombatCapsule(-8.5, -0.5, 5.5, -0.5, 5.5)],
    [CombatCapsule(-7, -2, 8, -2, 7)],
    [CombatCapsule(-5.5, -0.5, 6.5, -0.5, 8.5)],
    [CombatCapsule(-7, 3, 8, 3, 7)],
    [CombatCapsule(-8, 1, 5, 1, 6)],
    [CombatCapsule(-9.5, -0.5, 3.5, -0.5, 7.5)],
    [CombatCapsule(-10.5, -1.5, 4.5, -1.5, 6.5)],
    [CombatCapsule(-12.5, 0.5, 6.5, 0.5, 4.5)],
    [CombatCapsule(-9.5, 0.5, 6.5, 0.5, 4.5)],
  ];
  static const _fireBoltSpawn = [
    [CombatCapsule(-10.5, 0.5, 10.5, 0.5, 5.5)],
    [CombatCapsule(-13.5, -0.5, 10.5, -0.5, 5.5)],
    [CombatCapsule(-16.5, -0.5, 10.5, -0.5, 5.5)],
    [CombatCapsule(-18, 0, 10, 0, 6)],
  ];
  static const _fireBoltIdle = [
    [CombatCapsule(-10.5, 0.5, 10.5, 0.5, 5.5)],
    [CombatCapsule(-13.5, -0.5, 10.5, -0.5, 5.5)],
    [CombatCapsule(-16.5, -0.5, 10.5, -0.5, 5.5)],
    [CombatCapsule(-18, 0, 10, 0, 6)],
  ];
  static const _acidBoltSpawn = [
    [CombatCapsule(-0.5, 0.5, -0.5, 1.5, 6.5)],
    [CombatCapsule(-0.5, -0.5, -0.5, 1.5, 6.5)],
    [CombatCapsule(-0.5, -2.5, -0.5, 2.5, 6.5)],
    [CombatCapsule(-1, -2, -1, 2, 7)],
    [CombatCapsule(-0.5, -2.5, -0.5, 3.5, 5.5)],
    [CombatCapsule(0, -2, 0, 1, 6)],
    [CombatCapsule(0, -1, 0, -1, 7)],
    [CombatCapsule(-1.5, -1.5, -0.5, -1.5, 7.5)],
    [CombatCapsule(-2.5, 0.5, 2.5, 0.5, 5.5)],
    [CombatCapsule(-1.5, -0.5, 3.5, -0.5, 5.5)],
  ];
  static const _acidBoltIdle = [
    [CombatCapsule(-0.5, 0.5, -0.5, 1.5, 6.5)],
    [CombatCapsule(-0.5, -0.5, -0.5, 1.5, 6.5)],
    [CombatCapsule(-0.5, -2.5, -0.5, 2.5, 6.5)],
    [CombatCapsule(-1, -2, -1, 2, 7)],
    [CombatCapsule(-0.5, -2.5, -0.5, 3.5, 5.5)],
    [CombatCapsule(0, -2, 0, 1, 6)],
    [CombatCapsule(0, -1, 0, -1, 7)],
    [CombatCapsule(-1.5, -1.5, -0.5, -1.5, 7.5)],
    [CombatCapsule(-2.5, 0.5, 2.5, 0.5, 5.5)],
    [CombatCapsule(-1.5, -0.5, 3.5, -0.5, 5.5)],
  ];
  static const _darkBoltSpawn = [
    [CombatCapsule(-7.5, -1.5, -1.5, -1.5, 8.5)],
    [CombatCapsule(-10.5, -0.5, -0.5, -0.5, 7.5)],
    [CombatCapsule(-11.5, -0.5, -0.5, -0.5, 7.5)],
    [CombatCapsule(-10.5, -0.5, 1.5, -0.5, 7.5)],
    [CombatCapsule(-9.5, -0.5, 2.5, -0.5, 7.5)],
    [CombatCapsule(-10.5, 0.5, 2.5, 0.5, 7.5)],
    [CombatCapsule(-10.5, 0.5, 2.5, 0.5, 7.5)],
    [CombatCapsule(-11, -1, 3, -1, 7)],
    [CombatCapsule(-11, 0, 2, 0, 7)],
    [CombatCapsule(-7.5, -0.5, 0.5, -0.5, 7.5)],
  ];
  static const _darkBoltIdle = [
    [CombatCapsule(-7.5, -1.5, -1.5, -1.5, 8.5)],
    [CombatCapsule(-10.5, -0.5, -0.5, -0.5, 7.5)],
    [CombatCapsule(-11.5, -0.5, -0.5, -0.5, 7.5)],
    [CombatCapsule(-10.5, -0.5, 1.5, -0.5, 7.5)],
    [CombatCapsule(-9.5, -0.5, 2.5, -0.5, 7.5)],
    [CombatCapsule(-10.5, 0.5, 2.5, 0.5, 7.5)],
    [CombatCapsule(-10.5, 0.5, 2.5, 0.5, 7.5)],
    [CombatCapsule(-11, -1, 3, -1, 7)],
    [CombatCapsule(-11, 0, 2, 0, 7)],
    [CombatCapsule(-7.5, -0.5, 0.5, -0.5, 7.5)],
  ];
  static const _earthBoltSpawn = [
    [CombatCapsule(-6.5, -1.5, 4.5, -1.5, 4.5)],
    [CombatCapsule(-8, -1, 6, -1, 3)],
    [CombatCapsule(-8, -1, 6, -1, 3)],
    [CombatCapsule(-6.5, -0.5, 4.5, -0.5, 4.5)],
    [CombatCapsule(-7.5, -1.5, 5.5, -1.5, 3.5)],
    [CombatCapsule(-8, -1, 6, -1, 3)],
  ];
  static const _earthBoltIdle = [
    [CombatCapsule(-6.5, -1.5, 4.5, -1.5, 4.5)],
    [CombatCapsule(-8, -1, 6, -1, 3)],
    [CombatCapsule(-8, -1, 6, -1, 3)],
    [CombatCapsule(-6.5, -0.5, 4.5, -0.5, 4.5)],
    [CombatCapsule(-7.5, -1.5, 5.5, -1.5, 3.5)],
    [CombatCapsule(-8, -1, 6, -1, 3)],
  ];
  static const _holyBoltSpawn = [
    [CombatCapsule(0, 0, 10, 0, 2)],
    [CombatCapsule(0, 0, 9, 0, 3)],
  ];
  static const _holyBoltIdle = [
    [CombatCapsule(-5.5, -0.5, 8.5, -0.5, 4.5)],
    [CombatCapsule(-6.5, -0.5, 8.5, -0.5, 4.5)],
    [CombatCapsule(-6.5, 0.5, 8.5, 0.5, 5.5)],
    [CombatCapsule(-5.5, 0.5, 7.5, 0.5, 5.5)],
    [CombatCapsule(-7, 1, 8, 1, 5)],
    [CombatCapsule(-7, 1, 8, 1, 5)],
    [CombatCapsule(-8, 0, 10, 0, 4)],
    [CombatCapsule(-7, 0, 9, 0, 4)],
  ];
  static const _waterBoltSpawn = [
    [CombatCapsule(10.25, -0.25, 10.25, -0.25, 1.75)],
    [CombatCapsule(10.75, -2.75, 10.75, 2.25, 1.25)],
    [CombatCapsule(8.5, -1.5, 8.5, 0.5, 3.5)],
    [CombatCapsule(3.5, -0.5, 4.5, -0.5, 7.5)],
    [CombatCapsule(-5.5, -1, 5, -1, 7)],
  ];
  static const _waterBoltIdle = [
    [CombatCapsule(-7, -1, 5, -1, 7)],
    [CombatCapsule(-6.75, -0.75, 4.75, -0.75, 7.25)],
    [CombatCapsule(-6.5, -1, 4.5, -1, 7.5)],
    [CombatCapsule(-4.75, -0.25, 3.75, -0.25, 8.25)],
    [CombatCapsule(-5.25, -0.75, 3.25, -0.75, 8.75)],
    [CombatCapsule(-6, -1, 3, -1, 9)],
    [CombatCapsule(-6.75, -0.75, 3.25, -0.75, 8.75)],
    [CombatCapsule(-6.75, -0.75, 3.25, -0.75, 8.75)],
    [CombatCapsule(-7, -1, 5.5, -1, 6.5)],
    [CombatCapsule(-8, -1, 5, -1, 7)],
    [CombatCapsule(-9, -1, 5.5, -1, 6.5)],
    [CombatCapsule(-8.5, -1, 5, -1, 7)],
    [CombatCapsule(-9.5, -0.5, 6, -0.5, 6)],
    [CombatCapsule(-10, -0.5, 6, -0.5, 6)],
    [CombatCapsule(-9.5, -1, 6, -1, 6)],
    [CombatCapsule(-8.25, -1.25, 5.75, -1.25, 6.25)],
  ];
  static const _thunderBoltSpawn = [
    [CombatCapsule(-7.5, -0.5, 8.5, -0.5, 5.5)],
    [CombatCapsule(-3.5, 0.5, 3.5, 0.5, 9.5)],
    [CombatCapsule(-3, 0, 3, 0, 10)],
    [CombatCapsule(-3, 0, 3, 0, 10)],
    [CombatCapsule(-4, 0, 3, 0, 10)],
  ];
  static const _thunderBoltIdle = [
    [CombatCapsule(-7.5, -0.5, 8.5, -0.5, 5.5)],
    [CombatCapsule(-3.5, 0.5, 3.5, 0.5, 9.5)],
    [CombatCapsule(-3, 0, 3, 0, 10)],
    [CombatCapsule(-3, 0, 3, 0, 10)],
    [CombatCapsule(-4, 0, 3, 0, 10)],
  ];
  static const _npcSpearIdle = [
    [CombatCapsule(-27.75, 0, 27.75, 0, 3.75)],
    [CombatCapsule(-29.25, 0, 29.25, 0, 2.25)],
    [CombatCapsule(-30.75, 0, 30.75, 0, 0.75)],
    [CombatCapsule(-29.25, 0, 29.25, 0, 2.25)],
  ];
  static const _npcArrowIdle = [
    [CombatCapsule(-14.25, 0, 14.25, 0, 2.25)],
    [CombatCapsule(-15.75, 0, 15.75, 0, 0.75)],
  ];
  static const _goddessOrbSpawn = [
    [CombatCapsule(-21, 21, 24, 21, 10.5)],
    [CombatCapsule(-15, 21, 10.5, 21, 18)],
    [CombatCapsule(-12.75, 21.75, 9.75, 21.75, 18.75)],
  ];
  static const _goddessOrbIdle = [
    [CombatCapsule(-4.5, 19.5, 3, 19.5, 16.5)],
    [CombatCapsule(-4.5, 21, -1.5, 21, 15)],
    [CombatCapsule(-10.5, 21, 1.5, 21, 15)],
    [CombatCapsule(-3.75, 20.25, -3.75, 20.25, 15.75)],
    [CombatCapsule(-7.5, 21, 1.5, 21, 15)],
    [CombatCapsule(-4.5, 21, -1.5, 21, 15)],
    [CombatCapsule(-10.5, 21, 1.5, 21, 15)],
    [CombatCapsule(-3.75, 20.25, -3.75, 20.25, 15.75)],
  ];
  static const _shoggothOrbIdle = [
    [CombatCapsule(0.75, -0.75, 5.25, -0.75, 23.25)],
    [CombatCapsule(-0.75, -0.75, 3.75, -0.75, 23.25)],
    [CombatCapsule(0.75, -5.25, 3.75, -5.25, 23.25)],
    [CombatCapsule(9, -10.5, 9, -1.5, 21)],
    [CombatCapsule(6.75, -9.75, 6.75, -3.75, 23.25)],
    [CombatCapsule(2.25, -3.75, 5.25, -3.75, 23.25)],
  ];
  static const _voidClawSpawn = [
    [CombatCapsule(3, 4.5, 3, 6, 16.5)],
    [CombatCapsule(-6, 1.5, 22.5, 1.5, 21)],
  ];
  static const _voidClawIdle = [
    [CombatCapsule(-21, -3, 4.5, -3, 25.5)],
    [CombatCapsule(-20.25, -2.25, 5.25, -2.25, 24.75)],
    [CombatCapsule(-21, -3, 0, -3, 25.5)],
  ];
}
