/// GENERATED FILE. DO NOT EDIT BY HAND.
///
/// Generated by tool/generate_chunk_runtime_data.dart from:
/// - `assets/authoring/level/level_defs.json`
/// UI metadata for authored levels.
library;

import 'package:runner_core/levels/level_id.dart';

enum LevelUiStatus { active, deprecated }

class GeneratedLevelUiMetadata {
  const GeneratedLevelUiMetadata({
    required this.displayName,
    required this.status,
    required this.visualThemeId,
    required this.includeInBuild,
  });

  final String displayName;
  final LevelUiStatus status;
  final String visualThemeId;
  final bool includeInBuild;

  bool get isSelectableInStandardUi => includeInBuild && status == LevelUiStatus.active;
}

const Map<LevelId, GeneratedLevelUiMetadata> generatedLevelUiMetadataById =
    <LevelId, GeneratedLevelUiMetadata>{
  LevelId.forest: GeneratedLevelUiMetadata(
    displayName: 'Forest',
    status: LevelUiStatus.active,
    visualThemeId: 'forest',
    includeInBuild: true,
  ),
  LevelId.field: GeneratedLevelUiMetadata(
    displayName: 'Field',
    status: LevelUiStatus.active,
    visualThemeId: 'field',
    includeInBuild: true,
  ),
  LevelId.new_level: GeneratedLevelUiMetadata(
    displayName: 'New Level',
    status: LevelUiStatus.active,
    visualThemeId: 'new_level',
    includeInBuild: true,
  ),
};

const List<LevelId> generatedSelectableLevelIds = <LevelId>[
  LevelId.forest,
  LevelId.field,
  LevelId.new_level,
];

GeneratedLevelUiMetadata generatedLevelUiMetadataFor(LevelId levelId) {
  final metadata = generatedLevelUiMetadataById[levelId];
  if (metadata != null) {
    return metadata;
  }
  throw StateError('No generated UI metadata for levelId="${levelId.name}".');
}
