import 'dart:convert';

import 'package:runner_core/collision/terrain/terrain_authoring_polygon_signature.dart';
import 'package:runner_core/collision/terrain/terrain_authoring_seam_signature.dart';
import 'package:runner_core/collision/terrain/terrain_authoring_triangle_signature.dart';
import 'package:runner_core/collision/terrain/terrain_edge.dart';
import 'package:runner_core/collision/terrain/terrain_edge_id.dart';
import 'package:runner_core/collision/terrain/terrain_polygon.dart';
import 'package:runner_core/track/staged_terrain_data.dart';

import 'polygon_terrain_compilation.dart';
import 'polygon_terrain_seam_validation.dart';

const String _generatorOwnershipMarker =
    'Generated by tool/generate_chunk_runtime_data.dart';

const int _reservedCompilerChunkIndex = 0;

/// Materializes one accepted compiled chunk into Core's typed staged record.
StagedTerrainChunkData materializeStagedTerrainChunk(
  PolygonTerrainCompiledChunk compiled,
) {
  _validateCompiledChunk(compiled);
  final chunk = compiled.chunk;
  final polygons = compiled.renderGeometry.polygons.toList()
    ..sort((left, right) {
      final order = left.identity.compareTo(right.identity);
      return order != 0 ? order : left.sourcePath.compareTo(right.sourcePath);
    });
  final edges = compiled.geometry.edges.toList()
    ..sort((left, right) => left.id.compareTo(right.id));
  final triangles = compiled.triangles.toList()..sort();
  final placementLineage = compiled.placementLineage.toList()..sort();

  return StagedTerrainChunkData(
    chunkKey: chunk.chunkKey,
    id: chunk.id,
    revision: chunk.revision,
    status: chunk.status,
    levelId: chunk.levelId,
    tileSize: chunk.tileSize,
    width: chunk.width,
    height: chunk.height,
    difficulty: chunk.difficulty,
    assemblyGroupId: chunk.assemblyGroupId,
    authoringPolygonSignature: compiled.authoringPolygonSignature(),
    sourceSignature: compiled.geometry.sourceSignature(),
    edgeSignature: compiled.geometry.edgeSignature(),
    placementSignature: compiled.placementSignature(),
    triangleSignature: compiled.triangleSignature(),
    polygons: polygons.map(
      (polygon) => _materializePolygon(
        polygon,
        compiled.modeBySourceIdentity[polygon.identity]!,
      ),
    ),
    edges: edges.map(_materializeEdge),
    triangles: triangles.map(_materializeTriangle),
    placementLineage: placementLineage.map(_materializePlacementLineage),
  );
}

/// Materializes a seam-validated batch into Core's typed staged artifact.
StagedTerrainArtifactData materializeStagedTerrainArtifact(
  PolygonTerrainValidatedBatch batch,
) {
  final ordered = batch.chunks;
  if (ordered.isEmpty) {
    throw ArgumentError.value(batch, 'batch', 'Must contain chunks.');
  }
  _validateChunkKeys(ordered);
  final geometryVersions = ordered
      .map((compiled) => compiled.geometry.version)
      .toSet();
  if (geometryVersions.length != 1) {
    throw ArgumentError.value(
      geometryVersions,
      'chunks',
      'All staged chunks must use one compiler geometry version.',
    );
  }

  return StagedTerrainArtifactData(
    formatVersion: stagedTerrainArtifactFormatVersion,
    compilerGeometryVersion: geometryVersions.single,
    authoringPolygonSignatureFormat: terrainAuthoringPolygonSignatureFormat,
    authoringSeamSignatureFormat: terrainAuthoringSeamSignatureFormat,
    authoringSeamSignature: batch.seamSignature.digest,
    sourceSignatureFormat: stagedTerrainSourceSignatureFormat,
    edgeSignatureFormat: stagedTerrainEdgeSignatureFormat,
    placementSignatureFormat: stagedTerrainPlacementSignatureFormat,
    triangleSignatureFormat: terrainAuthoringTriangleSignatureFormat,
    chunks: ordered.map(materializeStagedTerrainChunk),
  );
}

/// Produces deterministic Dart records without a streamed chunk instance ID.
String renderStagedPolygonTerrainDart(PolygonTerrainValidatedBatch batch) {
  final artifact = materializeStagedTerrainArtifact(batch);

  final writer = _DartWriter()
    ..line('/// GENERATED FILE. DO NOT EDIT BY HAND.')
    ..line('///')
    ..line('/// $_generatorOwnershipMarker from canonical prefab-v3/chunk-v2')
    ..line('/// polygon source. Core admits it as runtime terrain authority.')
    ..line('library;')
    ..line()
    ..line("import 'package:runner_core/track/staged_terrain_data.dart';")
    ..line()
    ..line(
      'final StagedTerrainArtifactData stagedAuthoredTerrain = '
      'StagedTerrainArtifactData(',
    )
    ..line('  formatVersion: ${artifact.formatVersion},')
    ..line('  compilerGeometryVersion: ${artifact.compilerGeometryVersion},')
    ..line(
      '  authoringPolygonSignatureFormat: '
      '${_string(artifact.authoringPolygonSignatureFormat)},',
    )
    ..line(
      '  authoringSeamSignatureFormat: '
      '${_string(artifact.authoringSeamSignatureFormat)},',
    )
    ..line(
      '  authoringSeamSignature: '
      '${_string(artifact.authoringSeamSignature)},',
    )
    ..line(
      '  sourceSignatureFormat: '
      '${_string(artifact.sourceSignatureFormat)},',
    )
    ..line(
      '  edgeSignatureFormat: '
      '${_string(artifact.edgeSignatureFormat)},',
    )
    ..line(
      '  placementSignatureFormat: '
      '${_string(artifact.placementSignatureFormat)},',
    )
    ..line(
      '  triangleSignatureFormat: '
      '${_string(artifact.triangleSignatureFormat)},',
    )
    ..line('  chunks: <StagedTerrainChunkData>[');
  for (final chunk in artifact.chunks) {
    _writeChunk(writer, chunk, 4);
  }
  writer
    ..line('  ],')
    ..line(');');
  return writer.toString();
}

void _validateChunkKeys(List<PolygonTerrainCompiledChunk> chunks) {
  final exact = <String>{};
  final folded = <String, String>{};
  for (final compiled in chunks) {
    final key = compiled.chunk.chunkKey;
    if (!exact.add(key)) {
      throw ArgumentError.value(key, 'chunks', 'Duplicate chunk key.');
    }
    final canonical = key.toLowerCase();
    final previous = folded[canonical];
    if (previous != null) {
      throw ArgumentError.value(
        key,
        'chunks',
        'Chunk key case-collides with $previous.',
      );
    }
    folded[canonical] = key;
  }
}

void _validateCompiledChunk(PolygonTerrainCompiledChunk compiled) {
  final chunkKey = compiled.chunk.chunkKey;
  final polygons = compiled.renderGeometry.polygons;
  final polygonById = <(String?, String), int>{};
  for (final polygon in polygons) {
    _requireLocalIdentity(
      chunkKey: chunkKey,
      actualChunkKey: polygon.identity.chunkKey,
      compilerChunkIndex: polygon.identity.chunkIndex,
    );
    final key = (polygon.identity.placementKey, polygon.identity.shapeId);
    if (polygonById.containsKey(key)) {
      throw StateError('Duplicate staged polygon identity in $chunkKey: $key.');
    }
    polygonById[key] = polygon.vertices.length;
    if (!compiled.modeBySourceIdentity.containsKey(polygon.identity)) {
      throw StateError(
        'Staged polygon in $chunkKey has no authored role: $key.',
      );
    }
  }
  final collisionIds = compiled.geometry.polygons
      .map((polygon) => polygon.identity)
      .toSet();
  for (final polygon in polygons) {
    final mode = compiled.modeBySourceIdentity[polygon.identity]!;
    final collides = collisionIds.contains(polygon.identity);
    if ((mode == TerrainAuthoringPolygonMode.none) == collides) {
      throw StateError(
        'Staged polygon role was not partitioned in $chunkKey: '
        '${polygon.identity.shapeId}.',
      );
    }
  }
  for (final edge in compiled.geometry.edges) {
    _requireEdgeLocal(chunkKey, edge.id);
    final previous = edge.previousId;
    if (previous != null) _requireEdgeLocal(chunkKey, previous);
    final next = edge.nextId;
    if (next != null) _requireEdgeLocal(chunkKey, next);
  }
  for (final triangle in compiled.triangles) {
    _requireLocalIdentity(
      chunkKey: chunkKey,
      actualChunkKey: triangle.chunkKey,
      compilerChunkIndex: _reservedCompilerChunkIndex,
    );
    final vertexCount = polygonById[(triangle.placementKey, triangle.shapeId)];
    if (vertexCount == null ||
        triangle.first >= vertexCount ||
        triangle.second >= vertexCount ||
        triangle.third >= vertexCount) {
      throw StateError(
        'Triangle does not index a staged polygon in $chunkKey: '
        '${triangle.placementKey}/${triangle.shapeId}.',
      );
    }
  }
  for (final lineage in compiled.placementLineage) {
    _requireLocalIdentity(
      chunkKey: chunkKey,
      actualChunkKey: lineage.chunkKey,
      compilerChunkIndex: _reservedCompilerChunkIndex,
    );
    if (!polygonById.containsKey((lineage.placementKey, lineage.shapeId))) {
      throw StateError(
        'Placement lineage has no staged polygon in $chunkKey: '
        '${lineage.placementKey}/${lineage.shapeId}.',
      );
    }
  }
}

void _requireEdgeLocal(String chunkKey, TerrainEdgeId id) {
  _requireLocalIdentity(
    chunkKey: chunkKey,
    actualChunkKey: id.chunkKey,
    compilerChunkIndex: id.chunkIndex,
  );
}

void _requireLocalIdentity({
  required String chunkKey,
  required String actualChunkKey,
  required int compilerChunkIndex,
}) {
  if (actualChunkKey != chunkKey ||
      compilerChunkIndex != _reservedCompilerChunkIndex) {
    throw StateError(
      'Staged geometry for $chunkKey carries non-local compiler identity '
      '$compilerChunkIndex/$actualChunkKey.',
    );
  }
}

StagedTerrainPolygonData _materializePolygon(
  TerrainPolygon polygon,
  TerrainAuthoringPolygonMode mode,
) => StagedTerrainPolygonData(
  sourcePath: polygon.sourcePath,
  id: _materializeSourceId(polygon.identity),
  sourceVertices: polygon.sourceVertices.map(
    (point) => StagedTerrainPoint(point.xTicks, point.yTicks),
  ),
  vertices: polygon.vertices.map(
    (point) => StagedTerrainPoint(point.xTicks, point.yTicks),
  ),
  collisionMode: switch (mode) {
    TerrainAuthoringPolygonMode.solid => StagedTerrainCollisionMode.solid,
    TerrainAuthoringPolygonMode.oneWay => StagedTerrainCollisionMode.oneWay,
    TerrainAuthoringPolygonMode.none => StagedTerrainCollisionMode.none,
  },
  surfaceKind: polygon.surfaceKind,
  materialKey: polygon.materialKey,
);

StagedTerrainEdgeData _materializeEdge(TerrainEdge edge) =>
    StagedTerrainEdgeData(
      id: _materializeEdgeId(edge.id),
      start: StagedTerrainPoint(edge.start.xTicks, edge.start.yTicks),
      end: StagedTerrainPoint(edge.end.xTicks, edge.end.yTicks),
      tangent: StagedTerrainPoint(edge.tangent.xTicks, edge.tangent.yTicks),
      outwardNormal: StagedTerrainPoint(
        edge.outwardNormal.xTicks,
        edge.outwardNormal.yTicks,
      ),
      collisionMode: switch (edge.collisionMode) {
        TerrainCollisionMode.solid => StagedTerrainCollisionMode.solid,
        TerrainCollisionMode.oneWay => StagedTerrainCollisionMode.oneWay,
      },
      surfaceKind: edge.surfaceKind,
      materialKey: edge.materialKey,
      previousId: edge.previousId == null
          ? null
          : _materializeEdgeId(edge.previousId!),
      nextId: edge.nextId == null ? null : _materializeEdgeId(edge.nextId!),
      startJoin: _materializeVertexJoin(edge.startJoin),
      endJoin: _materializeVertexJoin(edge.endJoin),
    );

StagedTerrainTriangleData _materializeTriangle(
  PolygonTerrainTriangle triangle,
) => StagedTerrainTriangleData(
  sourceId: StagedTerrainSourceId(
    chunkKey: triangle.chunkKey,
    placementKey: triangle.placementKey,
    shapeId: triangle.shapeId,
  ),
  first: triangle.first,
  second: triangle.second,
  third: triangle.third,
);

StagedTerrainPlacementLineageData _materializePlacementLineage(
  PolygonTerrainPlacementLineage lineage,
) => StagedTerrainPlacementLineageData(
  sourceId: StagedTerrainSourceId(
    chunkKey: lineage.chunkKey,
    placementKey: lineage.placementKey,
    shapeId: lineage.shapeId,
  ),
  prefabKey: lineage.prefabKey,
  prefabId: lineage.prefabId,
  prefabRevision: lineage.prefabRevision,
  placementX: lineage.placementX,
  placementY: lineage.placementY,
  scaleTenths: lineage.scaleTenths,
  flipX: lineage.flipX,
  flipY: lineage.flipY,
);

StagedTerrainSourceId _materializeSourceId(TerrainSourceIdentity id) =>
    StagedTerrainSourceId(
      chunkKey: id.chunkKey,
      placementKey: id.placementKey,
      shapeId: id.shapeId,
    );

StagedTerrainEdgeId _materializeEdgeId(TerrainEdgeId id) => StagedTerrainEdgeId(
  sourceId: StagedTerrainSourceId(
    chunkKey: id.chunkKey,
    placementKey: id.placementKey,
    shapeId: id.shapeId,
  ),
  localEdgeIndex: id.localEdgeIndex,
  subEdgeIndex: id.subEdgeIndex,
);

StagedTerrainVertexJoin _materializeVertexJoin(TerrainVertexJoin join) =>
    switch (join) {
      TerrainVertexJoin.exposed => StagedTerrainVertexJoin.exposed,
      TerrainVertexJoin.connected => StagedTerrainVertexJoin.connected,
      TerrainVertexJoin.smooth => StagedTerrainVertexJoin.smooth,
    };

void _writeChunk(_DartWriter writer, StagedTerrainChunkData chunk, int indent) {
  final prefix = ' ' * indent;
  writer
    ..line('${prefix}StagedTerrainChunkData(')
    ..line('$prefix  chunkKey: ${_string(chunk.chunkKey)},')
    ..line('$prefix  id: ${_string(chunk.id)},')
    ..line('$prefix  revision: ${chunk.revision},')
    ..line('$prefix  status: ${_string(chunk.status)},')
    ..line('$prefix  levelId: ${_string(chunk.levelId)},')
    ..line('$prefix  tileSize: ${chunk.tileSize},')
    ..line('$prefix  width: ${chunk.width},')
    ..line('$prefix  height: ${chunk.height},')
    ..line('$prefix  difficulty: ${_string(chunk.difficulty)},')
    ..line('$prefix  assemblyGroupId: ${_string(chunk.assemblyGroupId)},')
    ..line(
      '$prefix  authoringPolygonSignature: '
      '${_string(chunk.authoringPolygonSignature)},',
    )
    ..line(
      '$prefix  sourceSignature: '
      '${_string(chunk.sourceSignature)},',
    )
    ..line(
      '$prefix  edgeSignature: '
      '${_string(chunk.edgeSignature)},',
    )
    ..line(
      '$prefix  placementSignature: '
      '${_string(chunk.placementSignature)},',
    )
    ..line(
      '$prefix  triangleSignature: '
      '${_string(chunk.triangleSignature)},',
    )
    ..line('$prefix  polygons: <StagedTerrainPolygonData>[');
  for (final polygon in chunk.polygons) {
    _writePolygon(writer, polygon, indent + 4);
  }
  writer.line('$prefix  ],');
  writer.line('$prefix  edges: <StagedTerrainEdgeData>[');
  for (final edge in chunk.edges) {
    _writeEdge(writer, edge, indent + 4);
  }
  writer.line('$prefix  ],');
  writer.line('$prefix  triangles: <StagedTerrainTriangleData>[');
  for (final triangle in chunk.triangles) {
    _writeTriangle(writer, triangle, indent + 4);
  }
  writer.line('$prefix  ],');
  writer.line(
    '$prefix  placementLineage: <StagedTerrainPlacementLineageData>[',
  );
  for (final lineage in chunk.placementLineage) {
    _writePlacementLineage(writer, lineage, indent + 4);
  }
  writer
    ..line('$prefix  ],')
    ..line('$prefix),');
}

void _writePolygon(
  _DartWriter writer,
  StagedTerrainPolygonData polygon,
  int indent,
) {
  final prefix = ' ' * indent;
  writer
    ..line('${prefix}StagedTerrainPolygonData(')
    ..line('$prefix  sourcePath: ${_string(polygon.sourcePath)},');
  _writeSourceId(writer, 'id', polygon.id, indent + 2);
  writer.line('$prefix  sourceVertices: <StagedTerrainPoint>[');
  for (final point in polygon.sourceVertices) {
    writer.line('$prefix    ${_point(point.xTicks, point.yTicks)},');
  }
  writer.line('$prefix  ],');
  writer.line('$prefix  vertices: <StagedTerrainPoint>[');
  for (final point in polygon.vertices) {
    writer.line('$prefix    ${_point(point.xTicks, point.yTicks)},');
  }
  writer
    ..line('$prefix  ],')
    ..line(
      '$prefix  collisionMode: '
      '${_collisionMode(polygon.collisionMode)},',
    )
    ..line('$prefix  surfaceKind: ${_nullableString(polygon.surfaceKind)},')
    ..line('$prefix  materialKey: ${_nullableString(polygon.materialKey)},')
    ..line('$prefix),');
}

void _writeEdge(_DartWriter writer, StagedTerrainEdgeData edge, int indent) {
  final prefix = ' ' * indent;
  writer.line('${prefix}StagedTerrainEdgeData(');
  _writeEdgeId(writer, 'id', edge.id, indent + 2);
  writer
    ..line('$prefix  start: ${_point(edge.start.xTicks, edge.start.yTicks)},')
    ..line('$prefix  end: ${_point(edge.end.xTicks, edge.end.yTicks)},')
    ..line(
      '$prefix  tangent: '
      '${_point(edge.tangent.xTicks, edge.tangent.yTicks)},',
    )
    ..line(
      '$prefix  outwardNormal: '
      '${_point(edge.outwardNormal.xTicks, edge.outwardNormal.yTicks)},',
    )
    ..line('$prefix  collisionMode: ${_collisionMode(edge.collisionMode)},')
    ..line('$prefix  surfaceKind: ${_nullableString(edge.surfaceKind)},')
    ..line('$prefix  materialKey: ${_nullableString(edge.materialKey)},');
  _writeNullableEdgeId(writer, 'previousId', edge.previousId, indent + 2);
  _writeNullableEdgeId(writer, 'nextId', edge.nextId, indent + 2);
  writer
    ..line('$prefix  startJoin: ${_vertexJoin(edge.startJoin)},')
    ..line('$prefix  endJoin: ${_vertexJoin(edge.endJoin)},')
    ..line('$prefix),');
}

void _writeTriangle(
  _DartWriter writer,
  StagedTerrainTriangleData triangle,
  int indent,
) {
  final prefix = ' ' * indent;
  writer.line('${prefix}StagedTerrainTriangleData(');
  _writeLocalSourceId(
    writer,
    'sourceId',
    chunkKey: triangle.sourceId.chunkKey,
    placementKey: triangle.sourceId.placementKey,
    shapeId: triangle.sourceId.shapeId,
    indent: indent + 2,
  );
  writer
    ..line('$prefix  first: ${triangle.first},')
    ..line('$prefix  second: ${triangle.second},')
    ..line('$prefix  third: ${triangle.third},')
    ..line('$prefix),');
}

void _writePlacementLineage(
  _DartWriter writer,
  StagedTerrainPlacementLineageData lineage,
  int indent,
) {
  final prefix = ' ' * indent;
  writer.line('${prefix}StagedTerrainPlacementLineageData(');
  _writeLocalSourceId(
    writer,
    'sourceId',
    chunkKey: lineage.sourceId.chunkKey,
    placementKey: lineage.sourceId.placementKey,
    shapeId: lineage.sourceId.shapeId,
    indent: indent + 2,
  );
  writer
    ..line('$prefix  prefabKey: ${_string(lineage.prefabKey)},')
    ..line('$prefix  prefabId: ${_string(lineage.prefabId)},')
    ..line('$prefix  prefabRevision: ${lineage.prefabRevision},')
    ..line('$prefix  placementX: ${lineage.placementX},')
    ..line('$prefix  placementY: ${lineage.placementY},')
    ..line('$prefix  scaleTenths: ${lineage.scaleTenths},')
    ..line('$prefix  flipX: ${lineage.flipX},')
    ..line('$prefix  flipY: ${lineage.flipY},')
    ..line('$prefix),');
}

void _writeSourceId(
  _DartWriter writer,
  String field,
  StagedTerrainSourceId id,
  int indent,
) {
  _writeLocalSourceId(
    writer,
    field,
    chunkKey: id.chunkKey,
    placementKey: id.placementKey,
    shapeId: id.shapeId,
    indent: indent,
  );
}

void _writeLocalSourceId(
  _DartWriter writer,
  String field, {
  required String chunkKey,
  required String? placementKey,
  required String shapeId,
  required int indent,
}) {
  final prefix = ' ' * indent;
  writer
    ..line('$prefix$field: StagedTerrainSourceId(')
    ..line('$prefix  chunkKey: ${_string(chunkKey)},')
    ..line('$prefix  placementKey: ${_nullableString(placementKey)},')
    ..line('$prefix  shapeId: ${_string(shapeId)},')
    ..line('$prefix),');
}

void _writeEdgeId(
  _DartWriter writer,
  String field,
  StagedTerrainEdgeId id,
  int indent,
) {
  final prefix = ' ' * indent;
  writer.line('$prefix$field: StagedTerrainEdgeId(');
  _writeLocalSourceId(
    writer,
    'sourceId',
    chunkKey: id.sourceId.chunkKey,
    placementKey: id.sourceId.placementKey,
    shapeId: id.sourceId.shapeId,
    indent: indent + 2,
  );
  writer
    ..line('$prefix  localEdgeIndex: ${id.localEdgeIndex},')
    ..line('$prefix  subEdgeIndex: ${id.subEdgeIndex},')
    ..line('$prefix),');
}

void _writeNullableEdgeId(
  _DartWriter writer,
  String field,
  StagedTerrainEdgeId? id,
  int indent,
) {
  if (id == null) {
    writer.line('${' ' * indent}$field: null,');
    return;
  }
  _writeEdgeId(writer, field, id, indent);
}

String _collisionMode(StagedTerrainCollisionMode mode) => switch (mode) {
  StagedTerrainCollisionMode.solid => 'StagedTerrainCollisionMode.solid',
  StagedTerrainCollisionMode.oneWay => 'StagedTerrainCollisionMode.oneWay',
  StagedTerrainCollisionMode.none => 'StagedTerrainCollisionMode.none',
};

String _vertexJoin(StagedTerrainVertexJoin join) => switch (join) {
  StagedTerrainVertexJoin.exposed => 'StagedTerrainVertexJoin.exposed',
  StagedTerrainVertexJoin.connected => 'StagedTerrainVertexJoin.connected',
  StagedTerrainVertexJoin.smooth => 'StagedTerrainVertexJoin.smooth',
};

String _point(int xTicks, int yTicks) => 'StagedTerrainPoint($xTicks, $yTicks)';

String _string(String value) => jsonEncode(value);

String _nullableString(String? value) =>
    value == null ? 'null' : _string(value);

final class _DartWriter {
  final StringBuffer _buffer = StringBuffer();

  void line([String value = '']) => _buffer.writeln(value);

  @override
  String toString() => _buffer.toString();
}
