// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVf_cQ5Xj15s_ZngbkeDXAokYCSCR8P7Y',
    appId: '1:964001571974:web:97acd9d8974e215dd81d07',
    messagingSenderId: '964001571974',
    projectId: 'rpg-runner-d7add',
    authDomain: 'rpg-runner-d7add.firebaseapp.com',
    storageBucket: 'rpg-runner-d7add.firebasestorage.app',
    measurementId: 'G-86SWFBNW26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_RE8QyjyVnoBQ-H59DCIbGbc39faaixA',
    appId: '1:964001571974:android:d48582bc9cde8cf2d81d07',
    messagingSenderId: '964001571974',
    projectId: 'rpg-runner-d7add',
    storageBucket: 'rpg-runner-d7add.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFNb8YfiG8TULypJb6t5c_obcSKxOTpk4',
    appId: '1:964001571974:ios:84c6faf57baaa0f4d81d07',
    messagingSenderId: '964001571974',
    projectId: 'rpg-runner-d7add',
    storageBucket: 'rpg-runner-d7add.firebasestorage.app',
    iosBundleId: 'com.example.rpgRunner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFNb8YfiG8TULypJb6t5c_obcSKxOTpk4',
    appId: '1:964001571974:ios:84c6faf57baaa0f4d81d07',
    messagingSenderId: '964001571974',
    projectId: 'rpg-runner-d7add',
    storageBucket: 'rpg-runner-d7add.firebasestorage.app',
    iosBundleId: 'com.example.rpgRunner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVf_cQ5Xj15s_ZngbkeDXAokYCSCR8P7Y',
    appId: '1:964001571974:web:2f0915a1e04e6c16d81d07',
    messagingSenderId: '964001571974',
    projectId: 'rpg-runner-d7add',
    authDomain: 'rpg-runner-d7add.firebaseapp.com',
    storageBucket: 'rpg-runner-d7add.firebasestorage.app',
    measurementId: 'G-XPENVW9P9L',
  );

}