import 'dart:convert';

import 'package:runner_core/collision/terrain/terrain_authoring_polygon_signature.dart';
import 'package:runner_core/collision/terrain/terrain_authoring_seam_signature.dart';
import 'package:runner_core/collision/terrain/terrain_edge.dart';
import 'package:runner_core/collision/terrain/terrain_edge_id.dart';
import 'package:runner_core/collision/terrain/terrain_polygon.dart';
import 'package:runner_core/track/staged_terrain_data.dart';

import 'generated_artifact_plan.dart';
import 'polygon_terrain_compilation.dart';
import 'polygon_terrain_seam_validation.dart';

const String stagedPolygonTerrainOutputPath =
    'packages/runner_core/lib/track/staged_authored_terrain.dart';
const String _generatorOwnershipMarker =
    'Generated by tool/generate_chunk_runtime_data.dart';
const String _sourceSignatureFormat = 'source-v1';
const String _edgeSignatureFormat = 'edges-v1';
const String _placementSignatureFormat = 'authoring-placement-v1';
const String _triangleSignatureFormat = 'authoring-triangles-v1';
const int _reservedCompilerChunkIndex = 0;

/// Renders accepted current-schema chunks as one future generated artifact.
///
/// The live generator does not register this artifact until the coordinated
/// prefab-v3/chunk-v2 source cutover. No empty placeholder is emitted.
GeneratedArtifact buildStagedPolygonTerrainArtifact({
  required PolygonTerrainValidatedBatch batch,
  String outputPath = stagedPolygonTerrainOutputPath,
}) => GeneratedArtifact(
  path: outputPath,
  content: renderStagedPolygonTerrainDart(batch),
);

/// Produces deterministic Dart records without a streamed chunk instance ID.
String renderStagedPolygonTerrainDart(PolygonTerrainValidatedBatch batch) {
  final ordered = batch.chunks;
  if (ordered.isEmpty) {
    throw ArgumentError.value(batch, 'batch', 'Must contain chunks.');
  }
  _validateChunkKeys(ordered);

  final geometryVersions = ordered
      .map((compiled) => compiled.geometry.version)
      .toSet();
  if (geometryVersions.length != 1) {
    throw ArgumentError.value(
      geometryVersions,
      'chunks',
      'All staged chunks must use one compiler geometry version.',
    );
  }
  for (final compiled in ordered) {
    _validateCompiledChunk(compiled);
  }

  final writer = _DartWriter()
    ..line('/// GENERATED FILE. DO NOT EDIT BY HAND.')
    ..line('///')
    ..line('/// $_generatorOwnershipMarker from canonical prefab-v3/chunk-v2')
    ..line('/// polygon source. This staged artifact is not runtime authority.')
    ..line('library;')
    ..line()
    ..line("import 'package:runner_core/track/staged_terrain_data.dart';")
    ..line()
    ..line(
      'final StagedTerrainArtifactData stagedAuthoredTerrain = '
      'StagedTerrainArtifactData(',
    )
    ..line('  formatVersion: $stagedTerrainArtifactFormatVersion,')
    ..line('  compilerGeometryVersion: ${geometryVersions.single},')
    ..line(
      '  authoringPolygonSignatureFormat: '
      '${_string(terrainAuthoringPolygonSignatureFormat)},',
    )
    ..line(
      '  authoringSeamSignatureFormat: '
      '${_string(terrainAuthoringSeamSignatureFormat)},',
    )
    ..line('  authoringSeamSignature: ${_string(batch.seamSignature.digest)},')
    ..line('  sourceSignatureFormat: ${_string(_sourceSignatureFormat)},')
    ..line('  edgeSignatureFormat: ${_string(_edgeSignatureFormat)},')
    ..line('  placementSignatureFormat: ${_string(_placementSignatureFormat)},')
    ..line('  triangleSignatureFormat: ${_string(_triangleSignatureFormat)},')
    ..line('  chunks: <StagedTerrainChunkData>[');
  for (final compiled in ordered) {
    _writeChunk(writer, compiled, 4);
  }
  writer
    ..line('  ],')
    ..line(');');
  return writer.toString();
}

void _validateChunkKeys(List<PolygonTerrainCompiledChunk> chunks) {
  final exact = <String>{};
  final folded = <String, String>{};
  for (final compiled in chunks) {
    final key = compiled.chunk.chunkKey;
    if (!exact.add(key)) {
      throw ArgumentError.value(key, 'chunks', 'Duplicate chunk key.');
    }
    final canonical = key.toLowerCase();
    final previous = folded[canonical];
    if (previous != null) {
      throw ArgumentError.value(
        key,
        'chunks',
        'Chunk key case-collides with $previous.',
      );
    }
    folded[canonical] = key;
  }
}

void _validateCompiledChunk(PolygonTerrainCompiledChunk compiled) {
  final chunkKey = compiled.chunk.chunkKey;
  final polygons = compiled.geometry.polygons;
  final polygonById = <(String?, String), int>{};
  for (final polygon in polygons) {
    _requireLocalIdentity(
      chunkKey: chunkKey,
      actualChunkKey: polygon.identity.chunkKey,
      compilerChunkIndex: polygon.identity.chunkIndex,
    );
    final key = (polygon.identity.placementKey, polygon.identity.shapeId);
    if (polygonById.containsKey(key)) {
      throw StateError('Duplicate staged polygon identity in $chunkKey: $key.');
    }
    polygonById[key] = polygon.vertices.length;
  }
  for (final edge in compiled.geometry.edges) {
    _requireEdgeLocal(chunkKey, edge.id);
    final previous = edge.previousId;
    if (previous != null) _requireEdgeLocal(chunkKey, previous);
    final next = edge.nextId;
    if (next != null) _requireEdgeLocal(chunkKey, next);
  }
  for (final triangle in compiled.triangles) {
    _requireLocalIdentity(
      chunkKey: chunkKey,
      actualChunkKey: triangle.chunkKey,
      compilerChunkIndex: _reservedCompilerChunkIndex,
    );
    final vertexCount = polygonById[(triangle.placementKey, triangle.shapeId)];
    if (vertexCount == null ||
        triangle.first >= vertexCount ||
        triangle.second >= vertexCount ||
        triangle.third >= vertexCount) {
      throw StateError(
        'Triangle does not index a staged polygon in $chunkKey: '
        '${triangle.placementKey}/${triangle.shapeId}.',
      );
    }
  }
  for (final lineage in compiled.placementLineage) {
    _requireLocalIdentity(
      chunkKey: chunkKey,
      actualChunkKey: lineage.chunkKey,
      compilerChunkIndex: _reservedCompilerChunkIndex,
    );
    if (!polygonById.containsKey((lineage.placementKey, lineage.shapeId))) {
      throw StateError(
        'Placement lineage has no staged polygon in $chunkKey: '
        '${lineage.placementKey}/${lineage.shapeId}.',
      );
    }
  }
}

void _requireEdgeLocal(String chunkKey, TerrainEdgeId id) {
  _requireLocalIdentity(
    chunkKey: chunkKey,
    actualChunkKey: id.chunkKey,
    compilerChunkIndex: id.chunkIndex,
  );
}

void _requireLocalIdentity({
  required String chunkKey,
  required String actualChunkKey,
  required int compilerChunkIndex,
}) {
  if (actualChunkKey != chunkKey ||
      compilerChunkIndex != _reservedCompilerChunkIndex) {
    throw StateError(
      'Staged geometry for $chunkKey carries non-local compiler identity '
      '$compilerChunkIndex/$actualChunkKey.',
    );
  }
}

void _writeChunk(
  _DartWriter writer,
  PolygonTerrainCompiledChunk compiled,
  int indent,
) {
  final chunk = compiled.chunk;
  final polygons = compiled.geometry.polygons.toList()
    ..sort((left, right) {
      final order = left.identity.compareTo(right.identity);
      return order != 0 ? order : left.sourcePath.compareTo(right.sourcePath);
    });
  final edges = compiled.geometry.edges.toList()
    ..sort((left, right) => left.id.compareTo(right.id));
  final triangles = compiled.triangles.toList()..sort(_compareTriangles);
  final placementLineage = compiled.placementLineage.toList()
    ..sort(_comparePlacementLineage);
  final prefix = ' ' * indent;
  writer
    ..line('${prefix}StagedTerrainChunkData(')
    ..line('$prefix  chunkKey: ${_string(chunk.chunkKey)},')
    ..line('$prefix  id: ${_string(chunk.id)},')
    ..line('$prefix  revision: ${chunk.revision},')
    ..line('$prefix  status: ${_string(chunk.status)},')
    ..line('$prefix  levelId: ${_string(chunk.levelId)},')
    ..line('$prefix  tileSize: ${chunk.tileSize},')
    ..line('$prefix  width: ${chunk.width},')
    ..line('$prefix  height: ${chunk.height},')
    ..line('$prefix  difficulty: ${_string(chunk.difficulty)},')
    ..line('$prefix  assemblyGroupId: ${_string(chunk.assemblyGroupId)},')
    ..line(
      '$prefix  authoringPolygonSignature: '
      '${_string(compiled.authoringPolygonSignature())},',
    )
    ..line(
      '$prefix  sourceSignature: '
      '${_string(compiled.geometry.sourceSignature())},',
    )
    ..line(
      '$prefix  edgeSignature: '
      '${_string(compiled.geometry.edgeSignature())},',
    )
    ..line(
      '$prefix  placementSignature: '
      '${_string(compiled.placementSignature())},',
    )
    ..line(
      '$prefix  triangleSignature: '
      '${_string(compiled.triangleSignature())},',
    )
    ..line('$prefix  polygons: <StagedTerrainPolygonData>[');
  for (final polygon in polygons) {
    _writePolygon(writer, polygon, indent + 4);
  }
  writer.line('$prefix  ],');
  writer.line('$prefix  edges: <StagedTerrainEdgeData>[');
  for (final edge in edges) {
    _writeEdge(writer, edge, indent + 4);
  }
  writer.line('$prefix  ],');
  writer.line('$prefix  triangles: <StagedTerrainTriangleData>[');
  for (final triangle in triangles) {
    _writeTriangle(writer, triangle, indent + 4);
  }
  writer.line('$prefix  ],');
  writer.line(
    '$prefix  placementLineage: <StagedTerrainPlacementLineageData>[',
  );
  for (final lineage in placementLineage) {
    _writePlacementLineage(writer, lineage, indent + 4);
  }
  writer
    ..line('$prefix  ],')
    ..line('$prefix),');
}

void _writePolygon(_DartWriter writer, TerrainPolygon polygon, int indent) {
  final prefix = ' ' * indent;
  writer
    ..line('${prefix}StagedTerrainPolygonData(')
    ..line('$prefix  sourcePath: ${_string(polygon.sourcePath)},');
  _writeSourceId(writer, 'id', polygon.identity, indent + 2);
  writer.line('$prefix  sourceVertices: <StagedTerrainPoint>[');
  for (final point in polygon.sourceVertices) {
    writer.line('$prefix    ${_point(point.xTicks, point.yTicks)},');
  }
  writer.line('$prefix  ],');
  writer.line('$prefix  vertices: <StagedTerrainPoint>[');
  for (final point in polygon.vertices) {
    writer.line('$prefix    ${_point(point.xTicks, point.yTicks)},');
  }
  writer
    ..line('$prefix  ],')
    ..line(
      '$prefix  collisionMode: '
      '${_collisionMode(polygon.collisionMode)},',
    )
    ..line('$prefix  surfaceKind: ${_nullableString(polygon.surfaceKind)},')
    ..line('$prefix  materialKey: ${_nullableString(polygon.materialKey)},')
    ..line('$prefix),');
}

void _writeEdge(_DartWriter writer, TerrainEdge edge, int indent) {
  final prefix = ' ' * indent;
  writer.line('${prefix}StagedTerrainEdgeData(');
  _writeEdgeId(writer, 'id', edge.id, indent + 2);
  writer
    ..line('$prefix  start: ${_point(edge.start.xTicks, edge.start.yTicks)},')
    ..line('$prefix  end: ${_point(edge.end.xTicks, edge.end.yTicks)},')
    ..line(
      '$prefix  tangent: '
      '${_point(edge.tangent.xTicks, edge.tangent.yTicks)},',
    )
    ..line(
      '$prefix  outwardNormal: '
      '${_point(edge.outwardNormal.xTicks, edge.outwardNormal.yTicks)},',
    )
    ..line('$prefix  collisionMode: ${_collisionMode(edge.collisionMode)},')
    ..line('$prefix  surfaceKind: ${_nullableString(edge.surfaceKind)},')
    ..line('$prefix  materialKey: ${_nullableString(edge.materialKey)},');
  _writeNullableEdgeId(writer, 'previousId', edge.previousId, indent + 2);
  _writeNullableEdgeId(writer, 'nextId', edge.nextId, indent + 2);
  writer
    ..line('$prefix  startJoin: ${_vertexJoin(edge.startJoin)},')
    ..line('$prefix  endJoin: ${_vertexJoin(edge.endJoin)},')
    ..line('$prefix),');
}

void _writeTriangle(
  _DartWriter writer,
  PolygonTerrainTriangle triangle,
  int indent,
) {
  final prefix = ' ' * indent;
  writer.line('${prefix}StagedTerrainTriangleData(');
  _writeLocalSourceId(
    writer,
    'sourceId',
    chunkKey: triangle.chunkKey,
    placementKey: triangle.placementKey,
    shapeId: triangle.shapeId,
    indent: indent + 2,
  );
  writer
    ..line('$prefix  first: ${triangle.first},')
    ..line('$prefix  second: ${triangle.second},')
    ..line('$prefix  third: ${triangle.third},')
    ..line('$prefix),');
}

void _writePlacementLineage(
  _DartWriter writer,
  PolygonTerrainPlacementLineage lineage,
  int indent,
) {
  final prefix = ' ' * indent;
  writer.line('${prefix}StagedTerrainPlacementLineageData(');
  _writeLocalSourceId(
    writer,
    'sourceId',
    chunkKey: lineage.chunkKey,
    placementKey: lineage.placementKey,
    shapeId: lineage.shapeId,
    indent: indent + 2,
  );
  writer
    ..line('$prefix  prefabKey: ${_string(lineage.prefabKey)},')
    ..line('$prefix  prefabId: ${_string(lineage.prefabId)},')
    ..line('$prefix  prefabRevision: ${lineage.prefabRevision},')
    ..line('$prefix  placementX: ${lineage.placementX},')
    ..line('$prefix  placementY: ${lineage.placementY},')
    ..line('$prefix  scaleTenths: ${lineage.scaleTenths},')
    ..line('$prefix  flipX: ${lineage.flipX},')
    ..line('$prefix  flipY: ${lineage.flipY},')
    ..line('$prefix),');
}

void _writeSourceId(
  _DartWriter writer,
  String field,
  TerrainSourceIdentity id,
  int indent,
) {
  _writeLocalSourceId(
    writer,
    field,
    chunkKey: id.chunkKey,
    placementKey: id.placementKey,
    shapeId: id.shapeId,
    indent: indent,
  );
}

void _writeLocalSourceId(
  _DartWriter writer,
  String field, {
  required String chunkKey,
  required String? placementKey,
  required String shapeId,
  required int indent,
}) {
  final prefix = ' ' * indent;
  writer
    ..line('$prefix$field: StagedTerrainSourceId(')
    ..line('$prefix  chunkKey: ${_string(chunkKey)},')
    ..line('$prefix  placementKey: ${_nullableString(placementKey)},')
    ..line('$prefix  shapeId: ${_string(shapeId)},')
    ..line('$prefix),');
}

void _writeEdgeId(
  _DartWriter writer,
  String field,
  TerrainEdgeId id,
  int indent,
) {
  final prefix = ' ' * indent;
  writer.line('$prefix$field: StagedTerrainEdgeId(');
  _writeLocalSourceId(
    writer,
    'sourceId',
    chunkKey: id.chunkKey,
    placementKey: id.placementKey,
    shapeId: id.shapeId,
    indent: indent + 2,
  );
  writer
    ..line('$prefix  localEdgeIndex: ${id.localEdgeIndex},')
    ..line('$prefix  subEdgeIndex: ${id.subEdgeIndex},')
    ..line('$prefix),');
}

void _writeNullableEdgeId(
  _DartWriter writer,
  String field,
  TerrainEdgeId? id,
  int indent,
) {
  if (id == null) {
    writer.line('${' ' * indent}$field: null,');
    return;
  }
  _writeEdgeId(writer, field, id, indent);
}

int _compareTriangles(
  PolygonTerrainTriangle left,
  PolygonTerrainTriangle right,
) {
  var order = left.chunkKey.compareTo(right.chunkKey);
  if (order != 0) return order;
  order = _compareNullable(left.placementKey, right.placementKey);
  if (order != 0) return order;
  order = left.shapeId.compareTo(right.shapeId);
  if (order != 0) return order;
  order = left.first.compareTo(right.first);
  if (order != 0) return order;
  order = left.second.compareTo(right.second);
  return order != 0 ? order : left.third.compareTo(right.third);
}

int _comparePlacementLineage(
  PolygonTerrainPlacementLineage left,
  PolygonTerrainPlacementLineage right,
) {
  var order = left.chunkKey.compareTo(right.chunkKey);
  if (order != 0) return order;
  order = left.placementKey.compareTo(right.placementKey);
  return order != 0 ? order : left.shapeId.compareTo(right.shapeId);
}

String _collisionMode(TerrainCollisionMode mode) => switch (mode) {
  TerrainCollisionMode.solid => 'StagedTerrainCollisionMode.solid',
  TerrainCollisionMode.oneWay => 'StagedTerrainCollisionMode.oneWay',
};

String _vertexJoin(TerrainVertexJoin join) => switch (join) {
  TerrainVertexJoin.exposed => 'StagedTerrainVertexJoin.exposed',
  TerrainVertexJoin.connected => 'StagedTerrainVertexJoin.connected',
  TerrainVertexJoin.smooth => 'StagedTerrainVertexJoin.smooth',
};

String _point(int xTicks, int yTicks) => 'StagedTerrainPoint($xTicks, $yTicks)';

String _string(String value) => jsonEncode(value);

String _nullableString(String? value) =>
    value == null ? 'null' : _string(value);

int _compareNullable(String? left, String? right) {
  if (identical(left, right)) return 0;
  if (left == null) return -1;
  if (right == null) return 1;
  return left.compareTo(right);
}

final class _DartWriter {
  final StringBuffer _buffer = StringBuffer();

  void line([String value = '']) => _buffer.writeln(value);

  @override
  String toString() => _buffer.toString();
}
