"""Regenerate portable flight capsules from catalog metadata and opaque pixels.

Run from the repo root with Python + Pillow and the Dart SDK. --dart accepts
the SDK executable; --check validates freshness without changing tracked files.
"""
import argparse
import json
from pathlib import Path
import shutil
import subprocess
import tempfile

from PIL import Image


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dart", default=shutil.which("dart"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    meta = json.loads(subprocess.check_output(
        [args.dart, "--suppress-analytics", "run", str(root / "tools/combat/export_projectile_art.dart")],
        cwd=root, text=True,
    ))
    lines = [
        "// Generated by tools/combat/generate_projectile_profiles.py; do not edit.",
        "import '../projectiles/projectile_id.dart';",
        "import '../snapshots/enums.dart';",
        "import 'combat_geometry.dart';", "",
        "/// Opaque flight silhouettes, relative to the render anchor at runtime scale.",
        "abstract final class ProjectilePoseCatalog {",
        "  static List<CombatCapsule> frame(ProjectileId id, AnimKey anim, int frame) {",
        "    final frames = switch ((id, anim)) {",
    ]
    shapes = []
    for projectile, render in meta.items():
        scale = render["scale"]
        for key, strip in render["keys"].items():
            image = Image.open(root / "assets/images" / strip["path"]).convert("RGBA")
            capsules = []
            for frame in range(strip["count"]):
                index = strip["start"] + frame
                columns = strip["cols"] or image.width // render["w"]
                row = strip["row"] + index // columns
                column = index % columns
                crop = image.crop((column * render["w"], row * render["h"],
                                   (column + 1) * render["w"], (row + 1) * render["h"]))
                # Exclude translucent glows. Fit total extents explicitly so
                # rounded ends never add a second radius outside the silhouette.
                bounds = crop.getchannel("A").point(lambda a: 255 if a >= 192 else 0).getbbox()
                if bounds is None:
                    raise ValueError(f"Empty flight frame: {projectile}/{key}/{frame}")
                x0, y0, x1, y1 = bounds
                x0, x1 = (x0 - render["x"]) * scale, (x1 - render["x"]) * scale
                y0, y1 = (y0 - render["y"]) * scale, (y1 - render["y"]) * scale
                radius = min(x1 - x0, y1 - y0) / 2
                cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
                values = (x0 + radius, cy, x1 - radius, cy, radius) if x1 - x0 >= y1 - y0 else (
                    cx, y0 + radius, cx, y1 - radius, radius)
                capsules.append("[CombatCapsule(" + ", ".join(f"{v:g}" for v in values) + ")]")
            name = "_" + projectile + key.capitalize()
            lines.append(f"      (ProjectileId.{projectile}, AnimKey.{key}) => {name},")
            shapes.append("  static const " + name + " = [\n    " + ",\n    ".join(capsules) + "\n  ];")
    lines += ["      _ => const <List<CombatCapsule>>[],", "    };",
              "    return frames.isEmpty ? const [] : frames[frame % frames.length];", "  }", ""]
    lines += shapes + ["}"]
    destination = root / "packages/runner_core/lib/combat/projectile_pose_catalog.dart"
    with tempfile.TemporaryDirectory(dir=root / ".tmp") as temp:
        output = Path(temp) / "projectile_pose_catalog.dart"
        output.write_text("\n".join(lines) + "\n", encoding="utf-8")
        subprocess.run([args.dart, "--suppress-analytics", "format", str(output)], check=True)
        content = output.read_text(encoding="utf-8")
    if args.check:
        if destination.read_text(encoding="utf-8") != content:
            raise SystemExit("Projectile combat profiles are stale; regenerate them.")
        print("Projectile combat profiles are current.")
    else:
        destination.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
