"""Generate beam part source rectangles from the imported PNG; --check checks drift.

Only source pixels are inspected. Destination geometry is reviewed in source
pixels at 1.5x scale, matching VoidcallerPoseCatalog's world-space beams.
"""
import argparse
import math
from pathlib import Path
import shutil
import subprocess
import tempfile
from PIL import Image


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--dart', default=shutil.which('dart'))
    args = parser.parse_args()
    if not args.dart:
        parser.error('Dart SDK executable missing; provide --dart.')
    root = Path(__file__).resolve().parents[2]
    (root / '.tmp').mkdir(exist_ok=True)
    image = Image.open(root / 'assets/images/entities/enemies/ancient_god_pack/voidcaller/sprite_sheet.png').convert('RGBA')

    def part(row, column, center_x, bottom_y=None, center_y=None, beam=False, diagonal=False):
        tile = image.crop((column*171,row*136,(column+1)*171,(row+1)*136))
        x0,y0,x1,y1 = tile.getchannel('A').getbbox()
        width,height = x1-x0,y1-y0
        rotation = 0
        if beam:
            width,height = 11,math.hypot(60,112) if diagonal else 112
            rotation = math.atan2(60,112) if diagonal else 0
            top = 26
        else:
            top = bottom_y-height if bottom_y is not None else center_y-height/2
        return f'RenderFramePart(source: RenderFrameRect({column*171+x0}, {row*136+y0}, {x1-x0}, {y1-y0}), position: Vec2({center_x-width/2:g}, {top:g}), size: Vec2({width:g}, {height:g}), rotationRadians: {rotation:.15g})'

    lines = ["// Generated by tools/combat/generate_voidcaller_effects.py; do not edit.","import '../contracts/render_anim_set_definition.dart';", "import '../contracts/render_frame_part.dart';", "import '../contracts/render_frame_rect.dart';", "import '../snapshots/enums.dart';", "import '../util/vec2.dart';", '', '/// Portal, beam and surface impact share the twelve-frame damage clock.', 'abstract final class VoidcallerEffectCatalog {']
    for diagonal in [False,True]:
        name = 'diagonal' if diagonal else 'vertical'
        startup,ground,portal = (10,13,14) if diagonal else (5,8,9)
        # Diagonal endcaps descend left in the source art and reference video.
        # Keep the ground mark at the pivot, with the portal 60 source pixels right.
        target_x = 46 if diagonal else 92
        center = target_x + 60 if diagonal else target_x
        lines += [f'  static const {name} = RenderAnimSetDefinition(', f'    frameWidth: 138, frameHeight: 146, anchorPoint: Vec2({target_x},146),', "    sourcesByKey: {AnimKey.hit: 'entities/enemies/ancient_god_pack/voidcaller/sprite_sheet.png'},", '    frameCountsByKey: {AnimKey.hit: 12}, stepTimeSecondsByKey: {AnimKey.hit: .08},', '    compositeFramesByKey: {AnimKey.hit: [']
        for frame in range(12):
            if frame<5:
                parts = [part(startup,frame,center,center_y=26), part(startup,frame,target_x,bottom_y=146)]
            else:
                phase=min(frame-5,5)
                parts=[part(portal,phase,center,center_y=26)]
                if frame<10:
                    parts += [part(7,frame%2,center,beam=True,diagonal=diagonal)]
                parts += [part(ground,phase,target_x,bottom_y=146)]
            lines.append('      ['+', '.join(parts)+'],')
        lines += ['    ]},','  );']
    lines += ['}']
    target=root/'packages/runner_core/lib/spell_impacts/voidcaller_effect_catalog.dart'
    with tempfile.TemporaryDirectory(dir=root/'.tmp') as directory:
        output=Path(directory)/target.name
        output.write_text('\n'.join(lines)+'\n',encoding='utf8')
        subprocess.run([args.dart,'--suppress-analytics','format',str(output)],check=True)
        content=output.read_text(encoding='utf8')
    if args.check:
        if target.read_text(encoding='utf8')!=content:
            raise SystemExit('Voidcaller beam metadata is stale.')
        print('Voidcaller beam metadata is current.')
    else:
        target.write_text(content,encoding='utf8')


if __name__=='__main__':
    main()
